# Generated by Django 6.0.4 on 2026-09-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('empresa', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=32)),
                ('telefone_normalizado', models.CharField(blank=True, max_length=20)),
                ('cargo_funcao', models.CharField(blank=True, max_length=120)),
                ('quantidade_obras', models.PositiveIntegerField(blank=True, null=True)),
                ('como_controla_hoje', models.CharField(blank=True, choices=[('EXCEL', 'Excel'), ('ERP', 'ERP'), ('SOFTWARE_OBRAS', 'Software de obras'), ('CONTROLES_PROPRIOS', 'Controles próprios'), ('WHATSAPP_PLANILHAS', 'WhatsApp + planilhas'), ('OUTRO', 'Outro')], max_length=32)),
                ('principal_dificuldade', models.CharField(blank=True, choices=[('MEDICOES_FATURAMENTO', 'Medições e faturamento'), ('CUSTOS_OBRA', 'Custos da obra'), ('FINANCEIRO', 'Financeiro'), ('COMPRAS', 'Compras'), ('DIARIO_CAMPO', 'Diário / campo'), ('VISAO_RESULTADO', 'Visão de resultado'), ('INFORMACOES_ESPALHADAS', 'Informações espalhadas'), ('OUTRO', 'Outro')], max_length=32)),
                ('mensagem', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('CONTATADO', 'Contatado'), ('DEMONSTRACAO_AGENDADA', 'Demonstração agendada'), ('PROPOSTA', 'Proposta'), ('GANHO', 'Ganho'), ('PERDIDO', 'Perdido')], default='NOVO', max_length=32)),
                ('observacao_comercial', models.TextField(blank=True)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=160)),
                ('utm_content', models.CharField(blank=True, max_length=160)),
                ('utm_term', models.CharField(blank=True, max_length=160)),
                ('landing_path', models.CharField(blank=True, max_length=300)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('gclid', models.CharField(blank=True, max_length=200)),
                ('fbclid', models.CharField(blank=True, max_length=200)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='site_public_status_c6f026_idx'), models.Index(fields=['utm_source', '-created_at'], name='site_public_utm_sou_c9ca6a_idx'), models.Index(fields=['utm_campaign', '-created_at'], name='site_public_utm_cam_914cf8_idx')],
            },
        ),
    ]
