# Generated by Django 6.0.4 on 2026-09-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_publico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiclead',
            name='billing_preference',
            field=models.CharField(blank=True, choices=[('MENSAL', 'Mensal'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=16),
        ),
    ]
