# Generated by Django 6.0.4 on 2026-09-15 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0005_usuarioempresa_grupo_usuarioempresa_obras_permitidas'),
        ('site_publico', '0002_publiclead_billing_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicidade', models.CharField(choices=[('MENSAL', 'Mensal'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=16)),
                ('valor_contratado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moeda', models.CharField(default='BRL', max_length=3)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATIVA', 'Ativa'), ('EM_ATRASO', 'Em atraso'), ('SUSPENSA', 'Suspensa'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada')], default='PENDENTE', max_length=16)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim_periodo', models.DateTimeField(blank=True, null=True)),
                ('proxima_cobranca', models.DateTimeField(blank=True, null=True)),
                ('grace_until', models.DateTimeField(blank=True, null=True)),
                ('gateway', models.CharField(choices=[('MERCADOPAGO', 'Mercado Pago'), ('INTERNO', 'Interno')], default='MERCADOPAGO', max_length=24)),
                ('gateway_subscription_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('gateway_plan_id', models.CharField(blank=True, max_length=120)),
                ('checkout_url', models.URLField(blank=True, max_length=700)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='empresas.empresa')),
                ('lead_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas', to='site_publico.publiclead')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EventoWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('MERCADOPAGO', 'Mercado Pago'), ('INTERNO', 'Interno')], default='MERCADOPAGO', max_length=24)),
                ('event_id', models.CharField(max_length=160)),
                ('event_type', models.CharField(blank=True, max_length=120)),
                ('resource_id', models.CharField(blank=True, max_length=160)),
                ('payload_hash', models.CharField(max_length=64)),
                ('status_processamento', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('PROCESSADO', 'Processado'), ('IGNORADO', 'Ignorado'), ('ERRO', 'Erro')], default='RECEBIDO', max_length=16)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['gateway', 'resource_id'], name='billing_eve_gateway_0bd84d_idx'), models.Index(fields=['status_processamento', 'received_at'], name='billing_eve_status__3b851e_idx')],
                'constraints': [models.UniqueConstraint(fields=('gateway', 'event_id'), name='unique_billing_webhook_event')],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('MERCADOPAGO', 'Mercado Pago'), ('INTERNO', 'Interno')], default='MERCADOPAGO', max_length=24)),
                ('gateway_payment_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('gateway_invoice_id', models.CharField(blank=True, max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moeda', models.CharField(default='BRL', max_length=3)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('CANCELADO', 'Cancelado'), ('ESTORNADO', 'Estornado'), ('EM_PROCESSAMENTO', 'Em processamento')], default='PENDENTE', max_length=20)),
                ('forma_pagamento', models.CharField(blank=True, max_length=80)),
                ('parcelas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('data_vencimento', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_status', models.CharField(blank=True, max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='billing.assinatura')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='assinatura',
            index=models.Index(fields=['empresa', 'status'], name='billing_ass_empresa_6a275f_idx'),
        ),
        migrations.AddIndex(
            model_name='assinatura',
            index=models.Index(fields=['gateway', 'gateway_subscription_id'], name='billing_ass_gateway_6e35a8_idx'),
        ),
        migrations.AddIndex(
            model_name='assinatura',
            index=models.Index(fields=['status', 'proxima_cobranca'], name='billing_ass_status_feb832_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['assinatura', 'status'], name='billing_pag_assinat_aca2b1_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['gateway', 'gateway_payment_id'], name='billing_pag_gateway_eda9fc_idx'),
        ),
    ]
