# Generated by Django 6.0.4 on 2026-09-22 02:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('empresas', '0005_usuarioempresa_grupo_usuarioempresa_obras_permitidas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_empresa', models.CharField(max_length=160)),
                ('nome_responsavel', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=40)),
                ('periodicidade', models.CharField(choices=[('MENSAL', 'Mensal'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=16)),
                ('status', models.CharField(choices=[('INICIADO', 'Iniciado'), ('CHECKOUT_CRIADO', 'Checkout criado'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('PAGO', 'Pago'), ('CONVERTIDO', 'Convertido'), ('FALHOU', 'Falhou'), ('CANCELADO', 'Cancelado'), ('EXPIRADO', 'Expirado')], db_index=True, default='INICIADO', max_length=24)),
                ('external_reference', models.CharField(db_index=True, max_length=80, unique=True)),
                ('gateway_subscription_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('gateway_checkout_url', models.URLField(blank=True, max_length=700)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=160)),
                ('utm_content', models.CharField(blank=True, max_length=160)),
                ('utm_term', models.CharField(blank=True, max_length=160)),
                ('gclid', models.CharField(blank=True, max_length=200)),
                ('fbclid', models.CharField(blank=True, max_length=200)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('consent_at', models.DateTimeField()),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assinatura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_origem', to='billing.assinatura')),
                ('empresa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_origem', to='empresas.empresa')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='billing_che_status_e3d1e0_idx'), models.Index(fields=['periodicidade', '-created_at'], name='billing_che_periodi_028ad0_idx'), models.Index(fields=['utm_source', '-created_at'], name='billing_che_utm_sou_7b4e80_idx')],
            },
        ),
    ]
