# Generated by Django 6.0.4 on 2026-05-05 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0006_carrega_dados_orla_lami'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrcamentoMedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=255)),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('preco_unitario_material', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('preco_unitario_mao_obra', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('preco_unitario_equipamentos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'Item de orcamento de medicao',
                'verbose_name_plural': 'Itens de orcamento de medicao',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MedicaoEmpreiteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('simples', 'Simples'), ('cumulativa', 'Cumulativa')], default='simples', max_length=20)),
                ('empreiteiro', models.CharField(max_length=180)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=30)),
                ('pix', models.CharField(blank=True, max_length=120)),
                ('numero', models.PositiveIntegerField(default=1)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('data_medicao', models.DateField()),
                ('retencao_tecnica', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('desconto_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicoes_empreiteiros', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Medicao de empreiteiro',
                'verbose_name_plural': 'Medicoes de empreiteiros',
                'ordering': ['-data_medicao', '-numero', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemMedicaoEmpreiteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=40)),
                ('descricao', models.CharField(max_length=255)),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('quantidade_periodo', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('item_orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicoes_empreiteiro', to='medicoes.itemorcamentomedicao')),
                ('medicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='medicoes.medicaoempreiteiro')),
            ],
            options={
                'verbose_name': 'Item de medicao de empreiteiro',
                'verbose_name_plural': 'Itens de medicao de empreiteiro',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoMedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('construtora', 'Construtora'), ('empreiteiro', 'Empreiteiro')], default='construtora', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_medicao', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Orcamento de medicao',
                'verbose_name_plural': 'Orcamentos de medicao',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='medicaoempreiteiro',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicoes_empreiteiro', to='medicoes.orcamentomedicao'),
        ),
        migrations.CreateModel(
            name='MedicaoConstrutora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('data_medicao', models.DateField()),
                ('retencao_tecnica', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('issqn', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('inss', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('desconto_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('faturamento_direto', models.BooleanField(default=False)),
                ('descricao_faturamento_direto', models.CharField(blank=True, max_length=255)),
                ('valor_faturamento_direto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes_construtora', to='medicoes.orcamentomedicao')),
            ],
            options={
                'verbose_name': 'Medicao da construtora',
                'verbose_name_plural': 'Medicoes da construtora',
                'ordering': ['-data_medicao', '-numero', '-id'],
            },
        ),
        migrations.AddField(
            model_name='itemorcamentomedicao',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='medicoes.orcamentomedicao'),
        ),
        migrations.CreateModel(
            name='ItemMedicaoConstrutora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_periodo', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('item_orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes_construtora', to='medicoes.itemorcamentomedicao')),
                ('medicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='medicoes.medicaoconstrutora')),
            ],
            options={
                'verbose_name': 'Item de medicao da construtora',
                'verbose_name_plural': 'Itens de medicao da construtora',
                'ordering': ['item_orcamento_id'],
                'constraints': [models.UniqueConstraint(fields=('medicao', 'item_orcamento'), name='unique_item_medicao_construtora')],
            },
        ),
        migrations.AddConstraint(
            model_name='medicaoconstrutora',
            constraint=models.UniqueConstraint(fields=('orcamento', 'numero'), name='unique_medicao_construtora_numero'),
        ),
    ]
