# Generated by Django 6.0.4 on 2026-05-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaoconstrutora',
            name='desconto_adicional_percentual',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='medicaoconstrutora',
            name='inss_percentual',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='medicaoconstrutora',
            name='issqn_percentual',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='medicaoconstrutora',
            name='retencao_tecnica_percentual',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='medicaoempreiteiro',
            name='desconto_adicional_percentual',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='medicaoempreiteiro',
            name='retencao_tecnica_percentual',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
    ]
