# Generated by Django 6.0.4 on 2026-05-14 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0017_faturamentodireto_data_oc_e_dados_park_mall'),
        ('medicoes', '0002_medicaoconstrutora_desconto_adicional_percentual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturamentoDiretoMedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faturamento_direto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vinculo_medicao', to='controles.faturamentodireto')),
                ('medicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturamentos_diretos', to='medicoes.medicaoconstrutora')),
            ],
            options={
                'verbose_name': 'Faturamento direto descontado na medicao',
                'verbose_name_plural': 'Faturamentos diretos descontados nas medicoes',
                'ordering': ['faturamento_direto__data_lancamento', 'id'],
            },
        ),
    ]
