# Generated by Django 6.0.4 on 2026-05-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0003_faturamentodiretomedicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorcamentomedicao',
            name='preco_unitario_equipamentos',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='itemorcamentomedicao',
            name='preco_unitario_mao_obra',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='itemorcamentomedicao',
            name='preco_unitario_material',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
