# Generated by Django 6.0.4 on 2026-05-28 16:30

import django.db.models.deletion
from django.db import migrations, models


def criar_empreiteiros_das_medicoes(apps, schema_editor):
    Empreiteiro = apps.get_model('medicoes', 'Empreiteiro')
    MedicaoEmpreiteiro = apps.get_model('medicoes', 'MedicaoEmpreiteiro')
    for medicao in MedicaoEmpreiteiro.objects.exclude(empreiteiro='').order_by('id'):
        nome = (medicao.empreiteiro or '').strip()
        if not nome:
            continue
        empreiteiro, _ = Empreiteiro.objects.get_or_create(
            nome=nome,
            defaults={
                'cpf_cnpj': medicao.cpf_cnpj or '',
                'pix': medicao.pix or '',
            },
        )
        updates = []
        if not empreiteiro.cpf_cnpj and medicao.cpf_cnpj:
            empreiteiro.cpf_cnpj = medicao.cpf_cnpj
            updates.append('cpf_cnpj')
        if not empreiteiro.pix and medicao.pix:
            empreiteiro.pix = medicao.pix
            updates.append('pix')
        if updates:
            empreiteiro.save(update_fields=updates)
        medicao.empreiteiro_cadastro = empreiteiro
        medicao.save(update_fields=['empreiteiro_cadastro'])


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0004_alter_itemorcamentomedicao_preco_unitario_equipamentos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empreiteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, unique=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=30)),
                ('pix', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=40)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empreiteiro',
                'verbose_name_plural': 'Empreiteiros',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='medicaoempreiteiro',
            name='empreiteiro_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicoes', to='medicoes.empreiteiro'),
        ),
        migrations.RunPython(criar_empreiteiros_das_medicoes, migrations.RunPython.noop),
    ]
