# Generated by Django 6.0.4 on 2026-05-28 17:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def preencher_valores_descontados(apps, schema_editor):
    FaturamentoDiretoMedicao = apps.get_model('medicoes', 'FaturamentoDiretoMedicao')
    for vinculo in FaturamentoDiretoMedicao.objects.select_related('faturamento_direto'):
        vinculo.percentual_descontado = Decimal('100')
        vinculo.valor_descontado = vinculo.faturamento_direto.valor_nota
        vinculo.save(update_fields=['percentual_descontado', 'valor_descontado'])


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0019_linhacronogramaobra_tipo'),
        ('medicoes', '0005_empreiteiro_medicaoempreiteiro_empreiteiro_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamentodiretomedicao',
            name='percentual_descontado',
            field=models.DecimalField(decimal_places=4, default=100, max_digits=7),
        ),
        migrations.AddField(
            model_name='faturamentodiretomedicao',
            name='valor_descontado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='faturamentodiretomedicao',
            name='faturamento_direto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_medicao', to='controles.faturamentodireto'),
        ),
        migrations.RunPython(preencher_valores_descontados, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='faturamentodiretomedicao',
            constraint=models.UniqueConstraint(fields=('medicao', 'faturamento_direto'), name='unique_faturamento_direto_por_medicao'),
        ),
    ]
