# Generated by Django 6.0.4 on 2026-07-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0006_faturamentodiretomedicao_percentual_descontado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaoconstrutora',
            name='desconto_adicional_reduz_base_nf',
            field=models.BooleanField(default=False),
        ),
    ]
