# Generated by Django 6.0.4 on 2026-07-27 18:36

from django.db import migrations, models


def classificar_grupos_existentes(apps, schema_editor):
    ItemOrcamentoMedicao = apps.get_model('medicoes', 'ItemOrcamentoMedicao')
    for item in ItemOrcamentoMedicao.objects.all():
        referencia = str(item.item or '').strip()
        if (
            referencia.isdigit()
            and not item.unidade
            and item.quantidade == 0
            and item.preco_unitario_material == 0
            and item.preco_unitario_mao_obra == 0
            and item.preco_unitario_equipamentos == 0
        ):
            item.tipo = 'grupo'
            item.save(update_fields=['tipo'])


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0007_medicaoconstrutora_desconto_adicional_reduz_base_nf'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamentomedicao',
            name='tipo',
            field=models.CharField(choices=[('grupo', 'Grupo / titulo'), ('item', 'Item medivel')], default='item', max_length=12),
        ),
        migrations.RunPython(classificar_grupos_existentes, migrations.RunPython.noop),
    ]
