# Generated by Django 6.0.4 on 2026-07-31 14:30

from django.db import migrations, models


def preencher_ordem_existente(apps, schema_editor):
    OrcamentoMedicao = apps.get_model('medicoes', 'OrcamentoMedicao')
    ItemOrcamentoMedicao = apps.get_model('medicoes', 'ItemOrcamentoMedicao')
    for orcamento in OrcamentoMedicao.objects.all():
        itens = ItemOrcamentoMedicao.objects.filter(orcamento=orcamento).order_by('id')
        for index, item in enumerate(itens):
            item.ordem = index
            item.save(update_fields=['ordem'])


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0008_itemorcamentomedicao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamentomedicao',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(preencher_ordem_existente, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='itemmedicaoconstrutora',
            options={'ordering': ['item_orcamento__ordem', 'item_orcamento_id'], 'verbose_name': 'Item de medicao da construtora', 'verbose_name_plural': 'Itens de medicao da construtora'},
        ),
        migrations.AlterModelOptions(
            name='itemorcamentomedicao',
            options={'ordering': ['ordem', 'id'], 'verbose_name': 'Item de orcamento de medicao', 'verbose_name_plural': 'Itens de orcamento de medicao'},
        ),
    ]
