# Generated by Django 6.0.4 on 2026-08-16 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_cria_empresa_ambar_e_vincula_usuarios'),
        ('medicoes', '0009_alter_itemmedicaoconstrutora_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreiteiro',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empreiteiros', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='empreiteiro',
            name='nome',
            field=models.CharField(max_length=180),
        ),
        migrations.AddConstraint(
            model_name='empreiteiro',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='unique_empreiteiro_empresa_nome'),
        ),
    ]
