# Generated by Django 6.0.4 on 2026-08-16 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_backfill_dados_ambar_fase2'),
        ('medicoes', '0010_empreiteiro_empresa_alter_empreiteiro_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreiteiro',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empreiteiros', to='empresas.empresa'),
        ),
    ]
