# Generated by Django 6.0.4 on 2026-09-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0014_alter_medicaoempreiteiro_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaoconstrutora',
            name='retencao_tecnica_reduz_base_nf',
            field=models.BooleanField(default=False),
        ),
    ]
