from django.urls import path

from . import views


app_name = 'social_automation'

urlpatterns = [
    path('', views.home, name='home'),
    path('perfis/', views.profile_list, name='profile_list'),
    path('perfis/novo/', views.profile_create, name='profile_create'),
    path('perfis/<int:profile_id>/', views.profile_detail, name='profile_detail'),
    path('instagram/callback/', views.instagram_callback, name='instagram_callback'),
    path('perfis/<int:profile_id>/instagram/conectar/', views.instagram_connect_start, name='instagram_connect_start'),
    path('perfis/<int:profile_id>/instagram/testar/', views.instagram_health, name='instagram_health'),
    path('perfis/<int:profile_id>/instagram/desconectar/', views.instagram_disconnect, name='instagram_disconnect'),
    path('perfis/<int:profile_id>/automacao/executar/', views.automation_run_now, name='automation_run_now'),
    path('perfis/<int:profile_id>/editar/', views.profile_update, name='profile_update'),
    path('perfis/<int:profile_id>/identidade-visual/', views.profile_visual_identity, name='profile_visual_identity'),
    path('perfis/<int:profile_id>/toggle/', views.profile_toggle, name='profile_toggle'),
    path('perfis/<int:profile_id>/gerar/', views.profile_generate, name='profile_generate'),
    path('perfis/<int:profile_id>/carrosseis/ia/novo/', views.profile_generate_carousel_ai, name='profile_generate_carousel_ai'),
    path('perfis/<int:profile_id>/imagens/', views.image_list, name='image_list'),
    path('perfis/<int:profile_id>/imagens/nova/', views.image_create, name='image_create'),
    path('imagens/<int:image_id>/editar/', views.image_update, name='image_update'),
    path('imagens/<int:image_id>/toggle/', views.image_toggle, name='image_toggle'),
    path('perfis/<int:profile_id>/carrosseis/templates/', views.carousel_template_list, name='carousel_template_list'),
    path('perfis/<int:profile_id>/carrosseis/templates/novo/', views.carousel_template_create, name='carousel_template_create'),
    path('carrosseis/templates/<int:template_id>/editar/', views.carousel_template_update, name='carousel_template_update'),
    path('conteudos/', views.content_list, name='content_list'),
    path('perfis/<int:profile_id>/conteudos/', views.content_list, name='profile_content_list'),
    path('conteudos/novo/', views.content_create, name='content_create'),
    path('perfis/<int:profile_id>/conteudos/novo/', views.content_create, name='profile_content_create'),
    path('conteudos/<int:content_id>/', views.content_detail, name='content_detail'),
    path('conteudos/<int:content_id>/editar/', views.content_update, name='content_update'),
    path('conteudos/<int:content_id>/renderizar/', views.content_render, name='content_render'),
    path('conteudos/<int:content_id>/retomar-ai-finished/', views.content_resume_ai_finished, name='content_resume_ai_finished'),
    path('conteudos/<int:content_id>/retomar-ai-finished/advance/', views.content_resume_ai_finished_advance, name='content_resume_ai_finished_advance'),
    path('conteudos/<int:content_id>/publicar-instagram/', views.content_publish_instagram, name='content_publish_instagram'),
    path('conteudos/<int:content_id>/aprovar/', views.content_approve, name='content_approve'),
    path('conteudos/<int:content_id>/rejeitar/', views.content_reject, name='content_reject'),
    path('conteudos/<int:content_id>/restaurar/', views.content_restore, name='content_restore'),
    path('conteudos/<int:content_id>/agendar/', views.content_schedule, name='content_schedule'),
    path('conteudos/<int:content_id>/desagendar/', views.content_unschedule, name='content_unschedule'),
    path('conteudos/<int:content_id>/excluir/', views.content_delete, name='content_delete'),
    path('conteudos/aprovar-lote/', views.content_bulk_approve, name='content_bulk_approve'),
    path('carrosseis/slides/<int:slide_id>/preview/', views.carousel_slide_preview, name='carousel_slide_preview'),
    path('carrosseis/slides/<int:slide_id>/gerar-imagem/', views.carousel_slide_generate_image, name='carousel_slide_generate_image'),
    path('carrosseis/slides/<int:slide_id>/revisar-ai-finished/', views.carousel_slide_rereview_ai_finished, name='carousel_slide_rereview_ai_finished'),
    path('public/<path:token>/', views.public_final_image, name='public_final_image'),
]
