# Generated by Django 6.0.4 on 2026-04-24 02:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controles', '0007_locacaoequipamento_numero_contrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sequencial', models.PositiveIntegerField(editable=False)),
                ('ano', models.PositiveIntegerField(editable=False)),
                ('cliente', models.CharField(max_length=150)),
                ('tipo_execucao', models.CharField(max_length=200)),
                ('data_proposta', models.DateField(default=django.utils.timezone.localdate)),
                ('servico_incluso', models.TextField(verbose_name='Servico incluido na proposta')),
                ('prazo_execucao', models.CharField(blank=True, max_length=200)),
                ('forma_pagamento', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('incluir_planilha', models.BooleanField(default=True)),
                ('bdi_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='BDI interno (%)')),
                ('local_fechamento', models.CharField(default='Campo Bom/RS', max_length=120)),
                ('data_encerramento', models.DateField(blank=True, null=True)),
                ('engenheiro_nome', models.CharField(default='Eng. Civil Patrick Ruppenthal de Lima', max_length=120)),
                ('engenheiro_crea', models.CharField(default='CREA/RS: 198.404', max_length=80)),
                ('situacao', models.CharField(choices=[('aguardando_resposta', 'Aguardando resposta'), ('em_revisao', 'Em revisao'), ('fechada', 'Fechada'), ('nao_foi_para_frente', 'Nao foi para frente'), ('cancelada', 'Cancelada')], default='aguardando_resposta', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('radar', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposta_comercial', to='controles.orcamentoradarobra')),
            ],
            options={
                'verbose_name': 'Proposta comercial',
                'verbose_name_plural': 'Propostas comerciais',
                'ordering': ['-ano', '-numero_sequencial'],
            },
        ),
        migrations.CreateModel(
            name='PropostaPlanilhaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Nr item')),
                ('descricao', models.CharField(max_length=255)),
                ('unidade', models.CharField(max_length=20, verbose_name='Und')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('preco_unit_material', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Preco unit material/equipamento')),
                ('preco_unit_mao_obra', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Preco unit mao de obra')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_planilha', to='propostas.proposta')),
            ],
            options={
                'verbose_name': 'Item da planilha orcamentaria',
                'verbose_name_plural': 'Itens da planilha orcamentaria',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropostaResumoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade_descricao', models.CharField(default='1 vb', max_length=40)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_resumo', to='propostas.proposta')),
            ],
            options={
                'verbose_name': 'Item resumido da proposta',
                'verbose_name_plural': 'Itens resumidos da proposta',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='proposta',
            constraint=models.UniqueConstraint(fields=('numero_sequencial', 'ano'), name='unique_numero_proposta_por_ano'),
        ),
    ]
