# Generated by Django 6.0.4 on 2026-04-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='planilha_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='propostas/planilhas/'),
        ),
    ]
