# Generated by Django 6.0.4 on 2026-08-16 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_cria_empresa_ambar_e_vincula_usuarios'),
        ('propostas', '0002_proposta_planilha_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propostas', to='empresas.empresa'),
        ),
    ]
