# Generated by Django 6.0.4 on 2026-08-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0005_alter_proposta_unique_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='engenheiro_crea',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='engenheiro_nome',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
