# Generated by Django 6.0.4 on 2026-08-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0006_alter_proposta_engenheiro_crea_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='proposta',
            name='unique_numero_proposta_empresa_ano',
        ),
        migrations.RemoveField(
            model_name='propostaresumoitem',
            name='proposta',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='radar',
        ),
        migrations.DeleteModel(
            name='PropostaPlanilhaItem',
        ),
        migrations.DeleteModel(
            name='PropostaResumoItem',
        ),
        migrations.DeleteModel(
            name='Proposta',
        ),
    ]
