# Generated by Django 6.0.4 on 2026-05-28 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0006_carrega_dados_orla_lami'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do diario')),
                ('responsavel_preenchimento', models.CharField(max_length=150)),
                ('responsavel_tecnico', models.CharField(blank=True, max_length=150)),
                ('condicao_climatica', models.CharField(blank=True, choices=[('ensolarado', 'Ensolarado'), ('nublado', 'Nublado'), ('chuvoso', 'Chuvoso'), ('parcialmente_nublado', 'Parcialmente nublado'), ('interrupcao_chuva', 'Interrupcao por chuva')], max_length=30)),
                ('turno', models.CharField(choices=[('manha', 'Manha'), ('tarde', 'Tarde'), ('integral', 'Integral'), ('noite', 'Noite')], default='integral', max_length=20)),
                ('situacao_obra', models.CharField(blank=True, choices=[('em_andamento', 'Em andamento'), ('paralisada', 'Paralisada'), ('sem_atividade', 'Sem atividade'), ('finalizada_parcialmente', 'Finalizada parcialmente')], max_length=30)),
                ('descricao_servicos', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ocorrencias_interferencias', models.TextField(blank=True)),
                ('pendencias', models.TextField(blank=True)),
                ('orientacoes', models.TextField(blank=True)),
                ('houve_visita', models.BooleanField(default=False)),
                ('visitante_nome', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('finalizado', 'Finalizado'), ('revisado', 'Revisado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_criados', to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='obras.obra')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_alterados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diario de obra',
                'verbose_name_plural': 'Diarios de obra',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('epi', 'Uso de EPI pela equipe'), ('sinalizacao', 'Sinalizacao da obra adequada'), ('limpeza', 'Organizacao e limpeza do canteiro'), ('equipamentos', 'Equipamentos em boas condicoes'), ('sem_acidente', 'Nao houve acidente/incidente'), ('conforme_projeto', 'Servicos executados conforme projeto'), ('niveis', 'Conferencia de niveis/alinhamentos'), ('materiais', 'Controle de materiais'), ('residuos', 'Controle de residuos'), ('clima', 'Condicoes climaticas adequadas')], max_length=40)),
                ('resultado', models.CharField(choices=[('conforme', 'Conforme'), ('nao_conforme', 'Nao conforme'), ('nao_aplica', 'Nao se aplica')], default='conforme', max_length=20)),
                ('observacoes', models.CharField(blank=True, max_length=255)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='diarios.diarioobra')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EfetivoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(choices=[('engenheiro', 'Engenheiro'), ('mestre_obras', 'Mestre de obras'), ('encarregado', 'Encarregado'), ('pedreiro', 'Pedreiro'), ('servente', 'Servente'), ('carpinteiro', 'Carpinteiro'), ('armador', 'Armador'), ('operador_maquina', 'Operador de maquina'), ('motorista', 'Motorista'), ('eletricista', 'Eletricista'), ('encanador', 'Encanador'), ('pintor', 'Pintor'), ('topografo', 'Topografo'), ('auxiliar', 'Auxiliar'), ('outros', 'Outros')], max_length=40)),
                ('nome_colaborador', models.CharField(blank=True, max_length=150)),
                ('empresa_equipe', models.CharField(blank=True, max_length=150)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('horario_entrada', models.TimeField(blank=True, null=True)),
                ('horario_saida', models.TimeField(blank=True, null=True)),
                ('total_horas', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('observacoes', models.CharField(blank=True, max_length=255)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efetivos', to='diarios.diarioobra')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EquipamentoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('escavadeira_hidraulica', 'Escavadeira hidraulica'), ('retroescavadeira', 'Retroescavadeira'), ('rolo_compactador', 'Rolo compactador'), ('caminhao_cacamba', 'Caminhao cacamba'), ('caminhao_munck', 'Caminhao munck'), ('betoneira', 'Betoneira'), ('compactador_solo', 'Compactador de solo'), ('bobcat', 'Bobcat'), ('caminhao_pipa', 'Caminhao pipa'), ('motoniveladora', 'Motoniveladora'), ('pa_carregadeira', 'Pa carregadeira'), ('placa_vibratoria', 'Placa vibratoria'), ('outros', 'Outros')], max_length=50)),
                ('identificacao', models.CharField(blank=True, max_length=120)),
                ('empresa_proprietario', models.CharField(blank=True, max_length=150)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('horimetro_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('horimetro_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_horas', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('situacao', models.CharField(choices=[('operando', 'Operando'), ('parado', 'Parado'), ('manutencao', 'Manutencao'), ('mobilizado', 'Mobilizado'), ('desmobilizado', 'Desmobilizado')], default='operando', max_length=30)),
                ('observacoes', models.CharField(blank=True, max_length=255)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='diarios.diarioobra')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FrenteServicoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('local_trecho', models.CharField(blank=True, max_length=180)),
                ('percentual_executado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('situacao', models.CharField(choices=[('executado', 'Executado'), ('em_execucao', 'Em execucao'), ('parcialmente_executado', 'Parcialmente executado'), ('nao_executado', 'Nao executado'), ('refeito_correcao', 'Refeito / correcao')], default='em_execucao', max_length=30)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frentes', to='diarios.diarioobra')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FotoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='diarios/fotos/%Y/%m/')),
                ('legenda', models.CharField(blank=True, max_length=180)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='diarios.diarioobra')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('frente_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos', to='diarios.frenteservicodiario')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criado', 'Criado'), ('editado', 'Editado'), ('finalizado', 'Finalizado'), ('reaberto', 'Reaberto'), ('cancelado', 'Cancelado'), ('foto_adicionada', 'Foto adicionada'), ('foto_removida', 'Foto removida')], max_length=30)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='diarios.diarioobra')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=150)),
                ('unidade', models.CharField(blank=True, max_length=30)),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('fornecedor', models.CharField(blank=True, max_length=150)),
                ('nota_fiscal', models.CharField(blank=True, max_length=80)),
                ('movimento', models.CharField(choices=[('recebido', 'Recebido'), ('utilizado', 'Utilizado'), ('devolvido', 'Devolvido')], default='recebido', max_length=20)),
                ('observacoes', models.CharField(blank=True, max_length=255)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='diarios.diarioobra')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('chuva', 'Chuva'), ('falta_material', 'Falta de material'), ('falta_projeto', 'Falta de projeto'), ('interferencia_rede', 'Interferencia de rede existente'), ('retrabalho', 'Retrabalho'), ('acidente_incidente', 'Acidente/incidente'), ('visita_fiscalizacao', 'Visita de fiscalizacao'), ('alteracao_escopo', 'Alteracao de escopo'), ('parada_equipe', 'Parada de equipe'), ('equipamento_parado', 'Equipamento parado'), ('atraso_fornecedor', 'Atraso de fornecedor'), ('outros', 'Outros')], max_length=40)),
                ('descricao', models.TextField()),
                ('impacto_prazo', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao'), ('parcial', 'Parcial')], default='nao', max_length=10)),
                ('impacto_financeiro', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao'), ('parcial', 'Parcial')], default='nao', max_length=10)),
                ('providencia', models.TextField(blank=True)),
                ('responsavel_providencia', models.CharField(blank=True, max_length=150)),
                ('prazo_solucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('resolvida', 'Resolvida'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='diarios.diarioobra')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='diarioobra',
            constraint=models.UniqueConstraint(fields=('obra', 'data'), name='unique_diario_por_obra_data'),
        ),
        migrations.AddConstraint(
            model_name='checklistdiario',
            constraint=models.UniqueConstraint(fields=('diario', 'item'), name='unique_item_checklist_diario'),
        ),
    ]
