# Generated by Django 6.0.4 on 2026-07-31 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


GRUPOS_PADRAO = ['Administrador', 'Diretoria', 'Financeiro', 'Engenharia', 'Compras', 'Administrativo', 'Obras', 'Consulta']


def criar_grupos_e_perfis(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('auth', 'User')
    PerfilUsuario = apps.get_model('usuarios', 'PerfilUsuario')
    for nome in GRUPOS_PADRAO:
        Group.objects.get_or_create(name=nome)
    for user in User.objects.all():
        PerfilUsuario.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0006_carrega_dados_orla_lami'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=40)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('setor', models.CharField(blank=True, choices=[('diretoria', 'Diretoria'), ('financeiro', 'Financeiro'), ('engenharia', 'Engenharia'), ('compras', 'Compras'), ('administrativo', 'Administrativo'), ('obras', 'Obras'), ('consulta', 'Consulta')], max_length=30)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='usuarios/avatares/')),
                ('dashboard_inicial', models.CharField(blank=True, max_length=120)),
                ('itens_por_pagina', models.PositiveIntegerField(default=25)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obras', models.ManyToManyField(blank=True, related_name='usuarios_vinculados', to='obras.obra')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfis de usuarios',
            },
        ),
        migrations.RunPython(criar_grupos_e_perfis, migrations.RunPython.noop),
    ]
