# Generated by Django 6.0.4 on 2026-08-23 16:09

import django.db.models.deletion
import social_automation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialBaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to=social_automation.models.social_base_image_upload_to)),
                ('nome', models.CharField(max_length=120)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('ativa', models.BooleanField(default=True)),
                ('vezes_usada', models.PositiveIntegerField(default=0)),
                ('ultima_utilizacao', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('plataforma', models.CharField(choices=[('instagram', 'Instagram')], default='instagram', max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=80, validators=[social_automation.models.validate_timezone_name])),
                ('modo_operacao', models.CharField(choices=[('manual', 'Manual'), ('semiautomatico', 'Semiautomatico'), ('automatico', 'Automatico')], default='semiautomatico', max_length=30)),
                ('posts_por_dia', models.PositiveSmallIntegerField(default=2)),
                ('horarios_publicacao', models.JSONField(default=list, validators=[social_automation.models.validate_horarios_publicacao])),
                ('estilo', models.TextField(blank=True)),
                ('instrucoes_ia', models.TextField(blank=True)),
                ('responder_comentarios', models.BooleanField(default=False)),
                ('limite_respostas', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['ativo', 'plataforma'], name='social_auto_ativo_ce29a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_image', models.ImageField(blank=True, null=True, upload_to=social_automation.models.social_final_image_upload_to)),
                ('frase', models.CharField(max_length=500)),
                ('legenda', models.TextField(blank=True)),
                ('hashtags', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aprovado', 'Aprovado'), ('agendado', 'Agendado'), ('publicando', 'Publicando'), ('publicado', 'Publicado'), ('erro', 'Erro'), ('rejeitado', 'Rejeitado')], default='rascunho', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('external_post_id', models.CharField(blank=True, max_length=120)),
                ('external_permalink', models.URLField(blank=True)),
                ('erro', models.TextField(blank=True)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('ultima_tentativa', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='social_automation.socialbaseimage')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='social_automation.socialprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_images', to='social_automation.socialprofile'),
        ),
        migrations.CreateModel(
            name='SocialContentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criado', 'Criado'), ('editado', 'Editado'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('agendado', 'Agendado'), ('desagendado', 'Desagendado'), ('restaurado', 'Restaurado'), ('excluido', 'Excluido')], max_length=30)),
                ('detalhe', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='social_automation.socialcontent')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['content', '-created_at'], name='social_auto_content_06208f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='socialcontent',
            index=models.Index(fields=['profile', 'status'], name='social_auto_profile_de8191_idx'),
        ),
        migrations.AddIndex(
            model_name='socialcontent',
            index=models.Index(fields=['status', 'scheduled_at'], name='social_auto_status_52a60a_idx'),
        ),
        migrations.AddIndex(
            model_name='socialbaseimage',
            index=models.Index(fields=['profile', 'ativa'], name='social_auto_profile_cbbb86_idx'),
        ),
    ]
