# Generated by Django 6.0.4 on 2026-08-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialbaseimage',
            name='text_position',
            field=models.CharField(choices=[('auto', 'Automatica'), ('left', 'Esquerda'), ('right', 'Direita'), ('top', 'Superior'), ('bottom', 'Inferior')], default='auto', max_length=10),
        ),
    ]
