# Generated by Django 6.0.4 on 2026-08-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_automation', '0002_socialbaseimage_text_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialbaseimage',
            name='primary_text_box_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='primary_text_box_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='primary_text_box_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='primary_text_box_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='secondary_text_align_horizontal',
            field=models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='secondary_text_align_vertical',
            field=models.CharField(choices=[('top', 'Topo'), ('middle', 'Meio'), ('bottom', 'Base')], default='middle', max_length=10),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='secondary_text_box_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='secondary_text_box_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='secondary_text_box_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='secondary_text_box_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='text_align_horizontal',
            field=models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='text_align_vertical',
            field=models.CharField(choices=[('top', 'Topo'), ('middle', 'Meio'), ('bottom', 'Base')], default='middle', max_length=10),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='text_box_preset',
            field=models.CharField(blank=True, choices=[('top_left', 'Superior esquerda'), ('top_right', 'Superior direita'), ('middle_left', 'Meio esquerda'), ('middle_right', 'Meio direita'), ('bottom_left', 'Inferior esquerda'), ('bottom_right', 'Inferior direita')], max_length=20),
        ),
        migrations.AlterField(
            model_name='socialbaseimage',
            name='text_position',
            field=models.CharField(choices=[('auto', 'Automatica'), ('auto_smart', 'Automatica inteligente'), ('left', 'Esquerda'), ('right', 'Direita'), ('top', 'Superior'), ('bottom', 'Inferior')], default='auto', max_length=10),
        ),
    ]
