# Generated by Django 6.0.4 on 2026-08-24 16:17

import social_automation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_automation', '0003_socialbaseimage_primary_text_box_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcontent',
            name='final_video',
            field=models.FileField(blank=True, null=True, upload_to=social_automation.models.social_final_video_upload_to),
        ),
        migrations.AddField(
            model_name='socialcontent',
            name='instagram_container_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='socialcontent',
            name='media_type',
            field=models.CharField(choices=[('image', 'Foto'), ('reel', 'Reel')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='reels_por_dia',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
