# Generated by Django 6.0.4 on 2026-08-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_automation', '0004_socialcontent_final_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcontent',
            name='instagram_container_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
