# Generated by Django 6.0.4 on 2026-08-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_automation', '0005_socialcontent_instagram_container_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialbaseimage',
            name='reel_primary_text_box_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='reel_primary_text_box_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='reel_primary_text_box_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='reel_primary_text_box_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='reel_secondary_text_align_horizontal',
            field=models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='reel_secondary_text_align_vertical',
            field=models.CharField(choices=[('top', 'Topo'), ('middle', 'Meio'), ('bottom', 'Base')], default='middle', max_length=10),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='reel_secondary_text_box_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='reel_secondary_text_box_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='reel_secondary_text_box_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='reel_secondary_text_box_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='reel_text_align_horizontal',
            field=models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='reel_text_align_vertical',
            field=models.CharField(choices=[('top', 'Topo'), ('middle', 'Meio'), ('bottom', 'Base')], default='middle', max_length=10),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='reel_text_box_preset',
            field=models.CharField(blank=True, choices=[('top_left', 'Superior esquerda'), ('top_center', 'Superior centro'), ('top_right', 'Superior direita'), ('center_left', 'Centro esquerda'), ('center_right', 'Centro direita'), ('bottom_left', 'Inferior esquerda'), ('bottom_center', 'Inferior centro'), ('bottom_right', 'Inferior direita')], max_length=20),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='reel_text_position',
            field=models.CharField(choices=[('auto', 'Automatica'), ('auto_smart', 'Automatica inteligente'), ('left', 'Esquerda'), ('right', 'Direita'), ('top', 'Superior'), ('bottom', 'Inferior')], default='auto', max_length=10),
        ),
    ]
