# Generated by Django 6.0.4 on 2026-08-26 00:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_automation', '0006_socialbaseimage_reel_primary_text_box_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialInstagramConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_user_id', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('BUSINESS', 'Business'), ('CREATOR', 'Creator'), ('DESCONHECIDO', 'Desconhecido')], default='DESCONHECIDO', max_length=30)),
                ('access_token_encrypted', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('last_validation_status', models.CharField(choices=[('nao_validado', 'Nao validado'), ('ok', 'OK'), ('erro', 'Erro')], default='nao_validado', max_length=30)),
                ('last_validation_error', models.CharField(blank=True, max_length=500)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_connection', to='social_automation.socialprofile')),
            ],
            options={
                'ordering': ['profile__nome'],
                'indexes': [models.Index(fields=['is_active', 'username'], name='social_auto_is_acti_3d3692_idx'), models.Index(fields=['instagram_user_id'], name='social_auto_instagr_d2bd00_idx')],
            },
        ),
    ]
