# Generated by Django 6.0.4 on 2026-08-29 14:39

import django.db.models.deletion
import social_automation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_automation', '0007_socialinstagramconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialbaseimage',
            name='ai_model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='ai_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'IA')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='ai_image_generation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='ai_image_mode',
            field=models.CharField(default='NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='carousel_ai_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='carousel_cta_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='carousel_default_cta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='carousel_default_slide_count',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='carousels_por_dia',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='image_ai_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialcontent',
            name='media_type',
            field=models.CharField(choices=[('image', 'Foto'), ('reel', 'Reel'), ('carousel', 'Carrossel')], default='image', max_length=10),
        ),
        migrations.CreateModel(
            name='SocialCarouselTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('aspect_ratio', models.CharField(choices=[('SQUARE', 'Quadrado 1:1'), ('PORTRAIT', 'Retrato 4:5')], default='SQUARE', max_length=20)),
                ('background_type', models.CharField(choices=[('SOLID', 'Cor solida'), ('GRADIENT', 'Gradiente'), ('IMAGE', 'Imagem')], default='GRADIENT', max_length=20)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=social_automation.models.social_carousel_template_upload_to)),
                ('background_color', models.CharField(default='#111827', max_length=20)),
                ('secondary_background_color', models.CharField(default='#334155', max_length=20)),
                ('text_color', models.CharField(default='#ffffff', max_length=20)),
                ('accent_color', models.CharField(default='#22c55e', max_length=20)),
                ('font_family', models.CharField(blank=True, max_length=80)),
                ('title_alignment', models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='left', max_length=10)),
                ('body_alignment', models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='left', max_length=10)),
                ('show_profile_name', models.BooleanField(default=True)),
                ('show_slide_number', models.BooleanField(default=True)),
                ('show_footer', models.BooleanField(default=True)),
                ('footer_text', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_templates', to='social_automation.socialprofile')),
            ],
            options={
                'ordering': ['profile__nome', '-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='socialcontent',
            name='carousel_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='social_automation.socialcarouseltemplate'),
        ),
        migrations.CreateModel(
            name='SocialCarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('slide_type', models.CharField(choices=[('COVER', 'Capa'), ('CONTENT', 'Conteudo'), ('CTA', 'CTA')], default='CONTENT', max_length=20)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('body', models.TextField(blank=True)),
                ('source_image', models.ImageField(blank=True, null=True, upload_to=social_automation.models.social_carousel_slide_source_upload_to)),
                ('rendered_image', models.ImageField(blank=True, null=True, upload_to=social_automation.models.social_carousel_slide_rendered_upload_to)),
                ('instagram_container_id', models.CharField(blank=True, max_length=120)),
                ('instagram_container_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_slides', to='social_automation.socialcontent')),
            ],
            options={
                'ordering': ['content', 'order', 'id'],
                'indexes': [models.Index(fields=['content', 'order'], name='social_auto_content_b0da87_idx')],
                'constraints': [models.UniqueConstraint(fields=('content', 'order'), name='unique_social_carousel_slide_order')],
            },
        ),
        migrations.AddIndex(
            model_name='socialcarouseltemplate',
            index=models.Index(fields=['profile', 'active'], name='social_auto_profile_0d9520_idx'),
        ),
    ]
