# Generated by Django 6.0.4 on 2026-08-29 21:22

import django.db.models.deletion
import social_automation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_automation', '0008_socialbaseimage_ai_model_socialbaseimage_ai_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialbaseimage',
            name='focal_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='focal_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='subject_position',
            field=models.CharField(choices=[('none', 'Sem assunto dominante'), ('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita'), ('bottom_left', 'Inferior esquerda'), ('bottom_center', 'Inferior centro'), ('bottom_right', 'Inferior direita')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='text_safe_zone',
            field=models.CharField(choices=[('auto', 'Automatica'), ('left', 'Esquerda'), ('right', 'Direita'), ('top', 'Superior'), ('bottom', 'Inferior'), ('full', 'Imagem toda')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='overlay_override',
            field=models.CharField(blank=True, choices=[('AUTO', 'Automatico'), ('NONE', 'Sem overlay'), ('DARK', 'Escuro'), ('LIGHT', 'Claro'), ('GRADIENT_LEFT', 'Gradiente esquerda'), ('GRADIENT_RIGHT', 'Gradiente direita'), ('GRADIENT_TOP', 'Gradiente superior'), ('GRADIENT_BOTTOM', 'Gradiente inferior')], max_length=30),
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='render_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='source_base_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carousel_slides', to='social_automation.socialbaseimage'),
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='text_color_override',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='visual_intent',
            field=models.CharField(choices=[('AUTO', 'Automatico'), ('HERO_LEFT', 'Hero esquerda'), ('HERO_RIGHT', 'Hero direita'), ('TEXT_TOP', 'Texto superior'), ('TEXT_BOTTOM', 'Texto inferior'), ('CENTER_CARD', 'Card central'), ('SPLIT_LEFT', 'Dividido esquerda'), ('SPLIT_RIGHT', 'Dividido direita'), ('MINIMAL', 'Minimal'), ('FULL_TEXT', 'Texto completo')], default='AUTO', max_length=30),
        ),
        migrations.CreateModel(
            name='SocialCarouselTemplateVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('allowed_slide_types', models.JSONField(blank=True, default=list)),
                ('aspect_ratio', models.CharField(blank=True, choices=[('SQUARE', 'Quadrado 1:1'), ('PORTRAIT', 'Retrato 4:5')], max_length=20)),
                ('layout_type', models.CharField(choices=[('AUTO', 'Automatico'), ('HERO_LEFT', 'Hero esquerda'), ('HERO_RIGHT', 'Hero direita'), ('TEXT_TOP', 'Texto superior'), ('TEXT_BOTTOM', 'Texto inferior'), ('CENTER_CARD', 'Card central'), ('SPLIT_LEFT', 'Dividido esquerda'), ('SPLIT_RIGHT', 'Dividido direita'), ('MINIMAL', 'Minimal'), ('FULL_TEXT', 'Texto completo')], default='AUTO', max_length=30)),
                ('title_alignment', models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='left', max_length=10)),
                ('body_alignment', models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='left', max_length=10)),
                ('title_max_lines', models.PositiveSmallIntegerField(default=3)),
                ('body_max_lines', models.PositiveSmallIntegerField(default=5)),
                ('overlay_enabled', models.BooleanField(default=True)),
                ('overlay_type', models.CharField(choices=[('AUTO', 'Automatico'), ('NONE', 'Sem overlay'), ('DARK', 'Escuro'), ('LIGHT', 'Claro'), ('GRADIENT_LEFT', 'Gradiente esquerda'), ('GRADIENT_RIGHT', 'Gradiente direita'), ('GRADIENT_TOP', 'Gradiente superior'), ('GRADIENT_BOTTOM', 'Gradiente inferior')], default='AUTO', max_length=30)),
                ('overlay_strength', models.PositiveSmallIntegerField(default=42)),
                ('show_footer', models.BooleanField(default=True)),
                ('show_slide_number', models.BooleanField(default=True)),
                ('show_brand', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='social_automation.socialcarouseltemplate')),
            ],
            options={
                'ordering': ['template', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='social_automation.socialcarouseltemplatevariant'),
        ),
        migrations.CreateModel(
            name='SocialVisualIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Identidade padrao', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=True)),
                ('primary_color', models.CharField(default='#111827', max_length=20)),
                ('secondary_color', models.CharField(default='#334155', max_length=20)),
                ('accent_color', models.CharField(default='#22c55e', max_length=20)),
                ('light_text_color', models.CharField(default='#ffffff', max_length=20)),
                ('dark_text_color', models.CharField(default='#111827', max_length=20)),
                ('font_primary', models.CharField(choices=[('SYSTEM_BOLD', 'Sistema negrito'), ('SYSTEM_REGULAR', 'Sistema regular'), ('SANS_BOLD', 'Sans negrito')], default='SYSTEM_BOLD', max_length=40)),
                ('font_secondary', models.CharField(choices=[('SYSTEM_BOLD', 'Sistema negrito'), ('SYSTEM_REGULAR', 'Sistema regular'), ('SANS_BOLD', 'Sans negrito')], default='SYSTEM_REGULAR', max_length=40)),
                ('font_weight_title', models.PositiveSmallIntegerField(default=700)),
                ('font_weight_body', models.PositiveSmallIntegerField(default=500)),
                ('brand_name', models.CharField(blank=True, max_length=120)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to=social_automation.models.social_visual_identity_logo_upload_to)),
                ('show_brand_name', models.BooleanField(default=True)),
                ('show_slide_number', models.BooleanField(default=True)),
                ('default_overlay_strength', models.PositiveSmallIntegerField(default=42)),
                ('default_margin', models.PositiveSmallIntegerField(default=76)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_identities', to='social_automation.socialprofile')),
            ],
            options={
                'ordering': ['profile__nome', '-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialBaseImageProtectedRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=2, max_digits=4)),
                ('y', models.DecimalField(decimal_places=2, max_digits=4)),
                ('width', models.DecimalField(decimal_places=2, max_digits=4)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('region_type', models.CharField(choices=[('subject', 'Assunto'), ('face', 'Rosto'), ('logo', 'Logo'), ('product', 'Produto'), ('custom', 'Personalizada')], default='subject', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protected_regions', to='social_automation.socialbaseimage')),
            ],
            options={
                'ordering': ['image', 'id'],
                'indexes': [models.Index(fields=['image', 'active'], name='social_auto_image_i_43c2a8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='socialcarouseltemplatevariant',
            index=models.Index(fields=['template', 'active', 'layout_type'], name='social_auto_templat_2da641_idx'),
        ),
        migrations.AddIndex(
            model_name='socialvisualidentity',
            index=models.Index(fields=['profile', 'active', 'is_default'], name='social_auto_profile_7ab9ab_idx'),
        ),
    ]
