# Generated by Django 6.0.4 on 2026-08-29 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_automation', '0009_socialbaseimage_focal_x_socialbaseimage_focal_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialbaseimage',
            name='ai_generation_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='analysis_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='analysis_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='analysis_model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='analysis_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimage',
            name='generation_purpose',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='socialbaseimageprotectedregion',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='socialbaseimageprotectedregion',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AI_ANALYSIS', 'Analise IA')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='media_intent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='media_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='semantic_visual_intent',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='ai_generated_images_reusable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='ai_image_daily_limit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='ai_image_mode',
            field=models.CharField(choices=[('NONE', 'Sem IA visual'), ('BANK_ONLY', 'Somente banco de midia'), ('AI_WHEN_NEEDED', 'IA quando necessario'), ('AI_ALWAYS', 'IA sempre')], default='NONE', max_length=30),
        ),
        migrations.CreateModel(
            name='SocialAIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('TEXT_GENERATION', 'Geracao de texto'), ('IMAGE_GENERATION', 'Geracao de imagem'), ('IMAGE_ANALYSIS', 'Analise de imagem')], max_length=30)),
                ('provider', models.CharField(default='openai', max_length=40)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('success', models.BooleanField(default=True)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usages', to='social_automation.socialbaseimage')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usages', to='social_automation.socialcontent')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usages', to='social_automation.socialprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['profile', 'operation', '-created_at'], name='social_auto_profile_8c5e00_idx'), models.Index(fields=['success', '-created_at'], name='social_auto_success_c02422_idx')],
            },
        ),
    ]
