# Generated by Django 6.0.4 on 2026-08-31 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_automation', '0010_socialbaseimage_ai_generation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcarouselslide',
            name='visual_treatment',
            field=models.CharField(choices=[('AUTO', 'Automatico'), ('IMAGE_HERO', 'Imagem destaque'), ('IMAGE_BACKGROUND', 'Imagem de fundo'), ('IMAGE_SPLIT', 'Imagem dividida'), ('EDITORIAL_CARD', 'Card editorial'), ('GRAPHIC_BACKGROUND', 'Background grafico'), ('MINIMAL_VISUAL', 'Minimal visual'), ('TEXT_ONLY', 'Somente texto')], default='AUTO', max_length=30),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='carousel_allow_same_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='carousel_image_density',
            field=models.CharField(choices=[('AUTO', 'Automatica'), ('LOW', 'Baixa'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('EVERY_SLIDE', 'Todos os slides')], default='AUTO', max_length=30),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='carousel_max_same_image_uses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='carousel_visual_mode',
            field=models.CharField(choices=[('STANDARD', 'Padrao'), ('VISUAL_RICH', 'Visual premium'), ('IMAGE_DRIVEN', 'Imagem em todos os slides')], default='STANDARD', max_length=30),
        ),
        migrations.AlterField(
            model_name='socialcarouselslide',
            name='visual_intent',
            field=models.CharField(choices=[('AUTO', 'Automatico'), ('HERO_LEFT', 'Hero esquerda'), ('HERO_RIGHT', 'Hero direita'), ('TEXT_TOP', 'Texto superior'), ('TEXT_BOTTOM', 'Texto inferior'), ('CENTER_CARD', 'Card central'), ('SPLIT_LEFT', 'Dividido esquerda'), ('SPLIT_RIGHT', 'Dividido direita'), ('MINIMAL', 'Minimal'), ('FULL_TEXT', 'Texto completo'), ('EDITORIAL_CARD', 'Card editorial'), ('IMAGE_BACKGROUND', 'Imagem de fundo'), ('IMAGE_BLUR_TEXT', 'Imagem desfocada com texto'), ('QUOTE_VISUAL', 'Frase visual'), ('GRAPHIC_DARK', 'Grafico escuro'), ('GRAPHIC_LIGHT', 'Grafico claro'), ('CTA_VISUAL', 'CTA visual')], default='AUTO', max_length=30),
        ),
        migrations.AlterField(
            model_name='socialcarouseltemplatevariant',
            name='layout_type',
            field=models.CharField(choices=[('AUTO', 'Automatico'), ('HERO_LEFT', 'Hero esquerda'), ('HERO_RIGHT', 'Hero direita'), ('TEXT_TOP', 'Texto superior'), ('TEXT_BOTTOM', 'Texto inferior'), ('CENTER_CARD', 'Card central'), ('SPLIT_LEFT', 'Dividido esquerda'), ('SPLIT_RIGHT', 'Dividido direita'), ('MINIMAL', 'Minimal'), ('FULL_TEXT', 'Texto completo'), ('EDITORIAL_CARD', 'Card editorial'), ('IMAGE_BACKGROUND', 'Imagem de fundo'), ('IMAGE_BLUR_TEXT', 'Imagem desfocada com texto'), ('QUOTE_VISUAL', 'Frase visual'), ('GRAPHIC_DARK', 'Grafico escuro'), ('GRAPHIC_LIGHT', 'Grafico claro'), ('CTA_VISUAL', 'CTA visual')], default='AUTO', max_length=30),
        ),
    ]
