# Generated by Django 6.0.4 on 2026-09-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_automation', '0011_socialcarouselslide_visual_treatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcarouselslide',
            name='slide_role',
            field=models.CharField(choices=[('HOOK_COVER', 'Hook de capa'), ('BELIEF_BREAK', 'Quebra de crenca'), ('CONTEXT', 'Contexto'), ('EXPLANATION', 'Explicacao'), ('INSIGHT', 'Insight'), ('VISUAL_PUNCH', 'Impacto visual'), ('ACTION_STEP', 'Acao pratica'), ('PROOF', 'Prova'), ('CONCLUSION', 'Conclusao'), ('CTA', 'CTA')], default='EXPLANATION', max_length=30),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='carousel_editorial_mode',
            field=models.CharField(choices=[('STANDARD', 'Padrao'), ('SOCIAL_PREMIUM', 'Social premium')], default='STANDARD', max_length=30),
        ),
        migrations.AlterField(
            model_name='socialcarouselslide',
            name='visual_intent',
            field=models.CharField(choices=[('AUTO', 'Automatico'), ('HERO_LEFT', 'Hero esquerda'), ('HERO_RIGHT', 'Hero direita'), ('COVER_HERO_RIGHT', 'Capa hero direita'), ('TEXT_TOP', 'Texto superior'), ('TEXT_BOTTOM', 'Texto inferior'), ('CENTER_CARD', 'Card central'), ('SPLIT_LEFT', 'Dividido esquerda'), ('SPLIT_RIGHT', 'Dividido direita'), ('MINIMAL', 'Minimal'), ('FULL_TEXT', 'Texto completo'), ('EDITORIAL_CARD', 'Card editorial'), ('IMAGE_BACKGROUND', 'Imagem de fundo'), ('IMAGE_BLUR_TEXT', 'Imagem desfocada com texto'), ('QUOTE_VISUAL', 'Frase visual'), ('GRAPHIC_DARK', 'Grafico escuro'), ('GRAPHIC_LIGHT', 'Grafico claro'), ('CTA_VISUAL', 'CTA visual'), ('COVER_HERO_LEFT', 'Capa hero esquerda'), ('COVER_HERO_CENTER', 'Capa hero central'), ('QUOTE_BIG', 'Frase grande'), ('EDITORIAL_SPLIT', 'Editorial dividido'), ('IMAGE_PUNCH_MINIMAL', 'Imagem impacto minimal'), ('DARK_MINIMAL_TEXT', 'Texto minimal escuro'), ('CTA_CLEAN', 'CTA limpo')], default='AUTO', max_length=30),
        ),
        migrations.AlterField(
            model_name='socialcarouseltemplatevariant',
            name='layout_type',
            field=models.CharField(choices=[('AUTO', 'Automatico'), ('HERO_LEFT', 'Hero esquerda'), ('HERO_RIGHT', 'Hero direita'), ('COVER_HERO_RIGHT', 'Capa hero direita'), ('TEXT_TOP', 'Texto superior'), ('TEXT_BOTTOM', 'Texto inferior'), ('CENTER_CARD', 'Card central'), ('SPLIT_LEFT', 'Dividido esquerda'), ('SPLIT_RIGHT', 'Dividido direita'), ('MINIMAL', 'Minimal'), ('FULL_TEXT', 'Texto completo'), ('EDITORIAL_CARD', 'Card editorial'), ('IMAGE_BACKGROUND', 'Imagem de fundo'), ('IMAGE_BLUR_TEXT', 'Imagem desfocada com texto'), ('QUOTE_VISUAL', 'Frase visual'), ('GRAPHIC_DARK', 'Grafico escuro'), ('GRAPHIC_LIGHT', 'Grafico claro'), ('CTA_VISUAL', 'CTA visual'), ('COVER_HERO_LEFT', 'Capa hero esquerda'), ('COVER_HERO_CENTER', 'Capa hero central'), ('QUOTE_BIG', 'Frase grande'), ('EDITORIAL_SPLIT', 'Editorial dividido'), ('IMAGE_PUNCH_MINIMAL', 'Imagem impacto minimal'), ('DARK_MINIMAL_TEXT', 'Texto minimal escuro'), ('CTA_CLEAN', 'CTA limpo')], default='AUTO', max_length=30),
        ),
    ]
