# Generated by Django 6.0.4 on 2026-09-01 01:48

import django.db.models.deletion
import social_automation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_automation', '0012_socialcarouselslide_slide_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaiusage',
            name='slide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usages', to='social_automation.socialcarouselslide'),
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='ai_composed_image',
            field=models.ImageField(blank=True, null=True, upload_to=social_automation.models.social_carousel_slide_composed_upload_to),
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='ai_composition_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='ai_composition_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='ai_composition_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='ai_composition_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='ai_composition_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('COMPOSING', 'Compondo'), ('REVIEWING', 'Revisando'), ('READY', 'Pronto'), ('ERROR', 'Erro'), ('NEEDS_RECOMPOSE', 'Recompor')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='ai_review_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='composition_type',
            field=models.CharField(choices=[('AUTO', 'Automatico'), ('TYPOGRAPHIC_HERO', 'Tipografia hero'), ('PHOTO_EDITORIAL', 'Foto editorial'), ('PHOTO_WITH_TYPE', 'Foto com tipografia'), ('SOCIAL_POST_CARD', 'Card social'), ('EDITORIAL_CARD', 'Card editorial'), ('SPLIT_COMPOSITION', 'Composicao dividida'), ('QUOTE_ART', 'Frase visual'), ('INFOGRAPHIC_LIGHT', 'Infografico leve'), ('NUMBER_STATEMENT', 'Numero/frase'), ('MINIMAL_STATEMENT', 'Minimal'), ('COLLAGE', 'Colagem'), ('ILLUSTRATIVE', 'Ilustrativo'), ('CTA_EDITORIAL', 'CTA editorial')], default='AUTO', max_length=30),
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='creative_plan_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='render_mode',
            field=models.CharField(choices=[('SYSTEM', 'Sistema'), ('AI_FINISHED', 'IA - arte final'), ('HYBRID', 'Hibrido')], default='SYSTEM', max_length=30),
        ),
        migrations.AddField(
            model_name='socialcarouselslide',
            name='rendered_text_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='carousel_creative_variation',
            field=models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Media'), ('HIGH', 'Alta')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='carousel_fallback_policy',
            field=models.CharField(choices=[('STRICT', 'Estrito'), ('ALLOW_SYSTEM_FALLBACK', 'Permitir compositor do sistema')], default='STRICT', max_length=30),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='carousel_generation_mode',
            field=models.CharField(choices=[('SYSTEM_COMPOSED', 'Sistema'), ('AI_DIRECTED', 'IA dirigida'), ('AI_FINISHED', 'IA - arte final')], default='SYSTEM_COMPOSED', max_length=30),
        ),
        migrations.AlterField(
            model_name='socialaiusage',
            name='operation',
            field=models.CharField(choices=[('TEXT_GENERATION', 'Geracao de texto'), ('IMAGE_GENERATION', 'Geracao de imagem'), ('IMAGE_ANALYSIS', 'Analise de imagem'), ('IDEATION', 'Ideacao'), ('CREATIVE_BLUEPRINT', 'Blueprint criativo'), ('COMPOSED_SLIDE', 'Composicao de slide'), ('COMPOSED_SLIDE_REVIEW', 'Review de slide composto')], max_length=30),
        ),
        migrations.CreateModel(
            name='SocialCarouselGenerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_mode', models.CharField(default='SYSTEM_COMPOSED', max_length=30)),
                ('status', models.CharField(choices=[('IDEATING', 'Gerando ideias'), ('IDEA_SELECTED', 'Ideia selecionada'), ('BLUEPRINT_READY', 'Blueprint pronto'), ('EDITORIAL_APPROVED', 'Editorial aprovado'), ('COMPOSING', 'Compondo'), ('REVIEWING', 'Revisando'), ('READY', 'Pronto'), ('PARTIAL', 'Parcial'), ('ERROR', 'Erro')], default='IDEATING', max_length=30)),
                ('selected_idea', models.JSONField(blank=True, default=dict)),
                ('selection_metadata', models.JSONField(blank=True, default=dict)),
                ('creative_blueprint', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carousel_generation_runs', to='social_automation.socialcontent')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_generation_runs', to='social_automation.socialprofile')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['profile', 'status', '-started_at'], name='social_auto_profile_3886b1_idx'), models.Index(fields=['content', '-started_at'], name='social_auto_content_644f7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialCreativeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('VISUAL_STYLE', 'Estilo visual'), ('CAROUSEL_STYLE', 'Estilo de carrossel'), ('COPY_STRUCTURE', 'Estrutura de copy'), ('HOOK', 'Hook'), ('CTA', 'CTA'), ('COMPOSITION', 'Composicao')], max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to=social_automation.models.social_creative_reference_upload_to)),
                ('text_reference', models.TextField(blank=True)),
                ('style_tags', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('ownership_type', models.CharField(choices=[('OWNED', 'Propria'), ('THIRD_PARTY_INSPIRATION', 'Inspiracao de terceiro'), ('LICENSED', 'Licenciada')], default='OWNED', max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creative_references', to='social_automation.socialprofile')),
            ],
            options={
                'ordering': ['profile__nome', 'reference_type', '-created_at'],
                'indexes': [models.Index(fields=['profile', 'active', 'reference_type'], name='social_auto_profile_cfc1a3_idx')],
            },
        ),
    ]
