# Generated by Django 6.0.4 on 2026-09-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_automation', '0013_socialaiusage_slide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialvisualidentity',
            name='font_scale',
            field=models.CharField(choices=[('SMALL', 'Pequena'), ('NORMAL', 'Normal'), ('LARGE', 'Grande'), ('XLARGE', 'Muito grande')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='socialvisualidentity',
            name='line_spacing',
            field=models.CharField(choices=[('COMPACT', 'Compacto'), ('NORMAL', 'Normal'), ('WIDE', 'Amplo')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='socialvisualidentity',
            name='text_outline',
            field=models.CharField(choices=[('AUTO', 'Padrao do sistema'), ('NONE', 'Sem contorno'), ('SOFT', 'Suave'), ('MEDIUM', 'Medio'), ('STRONG', 'Forte')], default='AUTO', max_length=20),
        ),
        migrations.AddField(
            model_name='socialvisualidentity',
            name='text_shadow',
            field=models.CharField(choices=[('AUTO', 'Padrao do sistema'), ('NONE', 'Sem sombra'), ('SOFT', 'Suave'), ('MEDIUM', 'Media')], default='AUTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='socialvisualidentity',
            name='font_primary',
            field=models.CharField(choices=[('SYSTEM_BOLD', 'Padrao do sistema'), ('SYSTEM_REGULAR', 'Sistema regular'), ('SANS_BOLD', 'Sans negrito'), ('MODERN', 'Moderna'), ('BOLD_SOCIAL', 'Impacto'), ('CONDENSED', 'Condensada'), ('ROUNDED', 'Arredondada'), ('EDITORIAL', 'Editorial')], default='SYSTEM_BOLD', max_length=40),
        ),
        migrations.AlterField(
            model_name='socialvisualidentity',
            name='font_secondary',
            field=models.CharField(choices=[('SYSTEM_BOLD', 'Padrao do sistema'), ('SYSTEM_REGULAR', 'Sistema regular'), ('SANS_BOLD', 'Sans negrito'), ('MODERN', 'Moderna'), ('BOLD_SOCIAL', 'Impacto'), ('CONDENSED', 'Condensada'), ('ROUNDED', 'Arredondada'), ('EDITORIAL', 'Editorial')], default='SYSTEM_REGULAR', max_length=40),
        ),
    ]
