# Generated by Django 6.0.4 on 2026-09-05 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_automation', '0014_socialvisualidentity_font_scale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialcontent',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('aprovado', 'Aprovado'), ('agendado', 'Agendado'), ('publicando', 'Publicando'), ('publish_confirmation_pending', 'Publicacao pendente de confirmacao'), ('publicado', 'Publicado'), ('erro', 'Erro'), ('rejeitado', 'Rejeitado')], default='rascunho', max_length=30),
        ),
        migrations.AlterField(
            model_name='socialcontentevent',
            name='acao',
            field=models.CharField(choices=[('criado', 'Criado'), ('editado', 'Editado'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('agendado', 'Agendado'), ('desagendado', 'Desagendado'), ('restaurado', 'Restaurado'), ('excluido', 'Excluido'), ('publish_prepared', 'Publicacao preparada'), ('publish_provider_called', 'Meta acionada'), ('publish_confirmed', 'Publicacao confirmada'), ('publish_ambiguous', 'Publicacao ambigua'), ('publish_reconciliation', 'Reconciliacao de publicacao'), ('publish_retry_released', 'Nova tentativa liberada')], max_length=30),
        ),
        migrations.CreateModel(
            name='SocialPublishAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('instagram', 'Instagram')], default='instagram', max_length=30)),
                ('container_id', models.CharField(blank=True, max_length=120)),
                ('fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('provider_called_at', models.DateTimeField(blank=True, null=True)),
                ('provider_response_at', models.DateTimeField(blank=True, null=True)),
                ('external_post_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('PREPARED', 'Preparada'), ('PROVIDER_CALLED', 'Meta acionada'), ('CONFIRMED', 'Confirmada'), ('AMBIGUOUS', 'Pendente de confirmacao'), ('FAILED_SAFE', 'Falha segura')], default='PREPARED', max_length=30)),
                ('error_class', models.CharField(blank=True, max_length=120)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_attempts', to='social_automation.socialcontent')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['content', 'provider', 'status'], name='social_auto_content_3e66cb_idx'), models.Index(fields=['status', '-started_at'], name='social_auto_status_b816e7_idx'), models.Index(fields=['external_post_id'], name='social_auto_externa_644ffe_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PREPARED', 'PROVIDER_CALLED', 'AMBIGUOUS'])), fields=('content', 'provider'), name='unique_active_social_publish_attempt')],
            },
        ),
    ]
