# Generated by Django 6.0.4 on 2026-09-07 01:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_automation', '0015_alter_socialcontent_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAutomationTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('already_running', 'Ja em execucao'), ('error', 'Erro')], default='ok', max_length=30)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('profiles_processed', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('scheduled_count', models.PositiveIntegerField(default=0)),
                ('published_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['status', '-started_at'], name='social_auto_status_9a122c_idx'), models.Index(fields=['-started_at'], name='social_auto_started_85ecce_idx')],
            },
        ),
    ]
