# Generated by Django 6.0.4 on 2026-09-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_automation', '0016_socialautomationtick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialcontent',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('aprovado', 'Aprovado'), ('retry_liberado_manual', 'Nova tentativa liberada manualmente'), ('agendado', 'Agendado'), ('publicando', 'Publicando'), ('publish_confirmation_pending', 'Publicacao pendente de confirmacao'), ('publicado', 'Publicado'), ('erro', 'Erro'), ('rejeitado', 'Rejeitado')], default='rascunho', max_length=30),
        ),
        migrations.AlterField(
            model_name='socialcontentevent',
            name='acao',
            field=models.CharField(choices=[('criado', 'Criado'), ('editado', 'Editado'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('agendado', 'Agendado'), ('desagendado', 'Desagendado'), ('restaurado', 'Restaurado'), ('excluido', 'Excluido'), ('publish_prepared', 'Publicacao preparada'), ('publish_provider_called', 'Meta acionada'), ('publish_confirmed', 'Publicacao confirmada'), ('publish_ambiguous', 'Publicacao ambigua'), ('publish_reconciliation', 'Reconciliacao de publicacao'), ('publish_retry_released', 'Nova tentativa liberada'), ('publish_not_published_operator', 'Nao publicada - confirmado pelo operador')], max_length=30),
        ),
        migrations.AlterField(
            model_name='socialpublishattempt',
            name='status',
            field=models.CharField(choices=[('PREPARED', 'Preparada'), ('PROVIDER_CALLED', 'Meta acionada'), ('CONFIRMED', 'Confirmada'), ('AMBIGUOUS', 'Pendente de confirmacao'), ('NOT_PUBLISHED_CONFIRMED_BY_OPERATOR', 'Nao publicada - confirmado pelo operador'), ('FAILED_SAFE', 'Falha segura')], default='PREPARED', max_length=40),
        ),
    ]
