# Generated by Django 6.0.4 on 2026-04-29 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0006_carrega_dados_orla_lami'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Centro de custo',
                'verbose_name_plural': 'Centros de custo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('mao_de_obra', 'Mao de obra'), ('material', 'Material'), ('equipamento', 'Equipamento'), ('terceiro', 'Terceiro'), ('administrativa', 'Administrativa'), ('outra', 'Outra')], default='outra', max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('aberto', 'Em aberto'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='financeiro.centrocusto')),
                ('despesa_obra', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conta_pagar_origem', to='obras.despesaobra')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Conta a pagar',
                'verbose_name_plural': 'Contas a pagar',
                'ordering': ['data_vencimento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150)),
                ('numero_nf', models.CharField(blank=True, max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('issqn_retido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('inss_retido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('retencao_tecnica', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outras_retencoes', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('aberto', 'Em aberto'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='financeiro.centrocusto')),
                ('nota_fiscal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conta_receber_origem', to='obras.notafiscal')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='obras.obra')),
                ('retencao_tecnica_obra', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conta_receber_origem', to='obras.retencaotecnicaobra')),
            ],
            options={
                'verbose_name': 'Conta a receber',
                'verbose_name_plural': 'Contas a receber',
                'ordering': ['data_vencimento', 'id'],
            },
        ),
    ]
