# Generated by Django 6.0.4 on 2026-05-08 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0014_ordemcomprageral_categoria_despesa_and_more'),
        ('financeiro', '0002_fornecedor_contapagar_fornecedor_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='item_ordem_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='controles.itemordemcomprageral'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='numero_nf',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='ordem_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='controles.ordemcomprageral'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='quantidade_oc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='valor_unitario_oc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
