# Generated by Django 6.0.4 on 2026-05-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_contapagar_item_ordem_compra_contapagar_numero_nf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
