# Generated by Django 6.0.4 on 2026-05-08 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0015_alter_notafiscalordemcomprageral_conta_pagar'),
        ('financeiro', '0004_contapagar_valor_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemContaPagarOrdemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_ordem_compra', to='financeiro.contapagar')),
                ('item_ordem_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_contas_pagar', to='controles.itemordemcomprageral')),
            ],
            options={
                'verbose_name': 'Item de OC da conta a pagar',
                'verbose_name_plural': 'Itens de OC das contas a pagar',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('conta', 'item_ordem_compra'), name='unique_item_oc_por_conta_pagar')],
            },
        ),
    ]
