# Generated by Django 6.0.4 on 2026-05-29 16:54

from django.db import migrations, models


def migrar_municipio_para_cidade_uf(apps, schema_editor):
    Fornecedor = apps.get_model('financeiro', 'Fornecedor')
    for fornecedor in Fornecedor.objects.all():
        municipio = (fornecedor.municipio or '').strip()
        if not municipio:
            continue
        cidade = municipio
        uf = ''
        if '/' in municipio:
            partes = municipio.rsplit('/', 1)
            cidade = partes[0].strip(' -')
            uf = partes[1].strip().upper()[:2]
        fornecedor.cidade = fornecedor.cidade or cidade
        fornecedor.uf = fornecedor.uf or uf
        fornecedor.save(update_fields=['cidade', 'uf'])


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_limpa_contas_pagar_e_pagas'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='bairro',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.RunPython(migrar_municipio_para_cidade_uf, migrations.RunPython.noop),
    ]
