# Generated by Django 6.0.4 on 2026-08-15 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_fornecedor_bairro_fornecedor_cidade_fornecedor_uf'),
        ('obras', '0006_carrega_dados_orla_lami'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receber', 'Entrada prevista'), ('pagar', 'Saida prevista')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('data_prevista', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pessoa', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='ativa', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previsoes_financeiras', to='financeiro.centrocusto')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previsoes_financeiras', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Previsao financeira',
                'verbose_name_plural': 'Previsoes financeiras',
                'ordering': ['data_prevista', 'id'],
                'indexes': [models.Index(fields=['data_prevista', 'status'], name='financeiro__data_pr_41249e_idx'), models.Index(fields=['tipo', 'status'], name='financeiro__tipo_06b4d3_idx')],
            },
        ),
    ]
