# Generated by Django 6.0.4 on 2026-08-16 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_cria_empresa_ambar_e_vincula_usuarios'),
        ('financeiro', '0014_previsaofinanceira'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fornecedor',
            name='unique_fornecedor_nome_documento',
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centros_custo', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='previsaofinanceira',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previsoes_financeiras', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='centrocusto',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='unique_centro_custo_empresa_nome'),
        ),
        migrations.AddConstraint(
            model_name='fornecedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome', 'cpf_cnpj'), name='unique_fornecedor_empresa_nome_documento'),
        ),
    ]
