# Generated by Django 6.0.4 on 2026-08-16 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_backfill_dados_ambar_fase2'),
        ('financeiro', '0015_remove_fornecedor_unique_fornecedor_nome_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrocusto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros_custo', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='previsaofinanceira',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='previsoes_financeiras', to='empresas.empresa'),
        ),
    ]
