# Generated by Django 6.0.4 on 2026-04-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_obra', models.CharField(max_length=150)),
                ('cliente', models.CharField(blank=True, max_length=150, null=True)),
                ('status_obra', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('paralisada', 'Paralisada')], default='em_andamento', max_length=20)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('valor_contrato', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('aditivos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('projecao_despesa', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('despesa_real', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('retencoes_tecnicas', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impostos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_notas', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
