# Generated by Django 6.0.4 on 2026-04-20 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='status_obra',
            field=models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('paralisada', 'Paralisada')], default='em_andamento', max_length=20),
        ),
        migrations.CreateModel(
            name='AditivoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos_registrados', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Aditivo de contrato',
                'verbose_name_plural': 'Aditivos de contrato',
                'ordering': ['-data_referencia', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DespesaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField()),
                ('categoria', models.CharField(choices=[('mao_de_obra', 'Mao de obra'), ('material', 'Material'), ('equipamento', 'Equipamento'), ('terceiro', 'Terceiro'), ('administrativa', 'Administrativa'), ('outra', 'Outra')], default='outra', max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_registradas', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Despesa da obra',
                'verbose_name_plural': 'Despesas da obra',
                'ordering': ['-data_referencia', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('data_emissao', models.DateField()),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('emitida', 'Emitida'), ('cancelada', 'Cancelada'), ('recebida', 'Recebida')], default='emitida', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Nota fiscal',
                'verbose_name_plural': 'Notas fiscais',
                'ordering': ['-data_emissao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ImpostoNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('simples', 'Simples'), ('pis', 'PIS'), ('cofins', 'COFINS'), ('csll', 'CSLL'), ('irpj', 'IRPJ'), ('iss', 'ISS'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impostos', to='obras.notafiscal')),
            ],
            options={
                'verbose_name': 'Imposto da nota fiscal',
                'verbose_name_plural': 'Impostos da nota fiscal',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RetencaoNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inss', 'INSS'), ('iss', 'ISS'), ('irrf', 'IRRF'), ('pis_cofins_csll', 'PIS/COFINS/CSLL'), ('outra', 'Outra')], default='outra', max_length=30)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retencoes', to='obras.notafiscal')),
            ],
            options={
                'verbose_name': 'Retencao da nota fiscal',
                'verbose_name_plural': 'Retencoes da nota fiscal',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='notafiscal',
            constraint=models.UniqueConstraint(fields=('obra', 'numero'), name='unique_numero_nota_por_obra'),
        ),
    ]
