# Generated by Django 6.0.4 on 2026-04-21 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_alter_obra_status_obra_aditivocontrato_despesaobra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aditivocontrato',
            name='tipo',
            field=models.CharField(choices=[('aditivo', 'Aditivo'), ('supressao', 'Supressao')], default='aditivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='obra',
            name='status_obra',
            field=models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluida'), ('paralisada', 'Paralisada')], default='em_andamento', max_length=20),
        ),
        migrations.CreateModel(
            name='RetencaoTecnicaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retencoes_tecnicas_registradas', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Retencao tecnica da obra',
                'verbose_name_plural': 'Retencoes tecnicas da obra',
                'ordering': ['-data_referencia', '-id'],
            },
        ),
    ]
