# Generated by Django 6.0.4 on 2026-08-16 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_backfill_dados_ambar_fase2'),
        ('obras', '0007_obra_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='empresas.empresa'),
        ),
    ]
