# Generated by Django 6.0.4 on 2026-04-23 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VeiculoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('caminhao', 'Caminhao'), ('maquina', 'Maquina'), ('equipamento', 'Equipamento'), ('outro', 'Outro')], default='carro', max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veiculo/Maquina',
                'verbose_name_plural': 'Veiculos/Maquinas',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAbastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abastecimento', models.DateField()),
                ('posto', models.CharField(max_length=150)),
                ('responsavel', models.CharField(max_length=120)),
                ('litros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_litro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos', to='controles.veiculomaquina')),
            ],
            options={
                'verbose_name': 'Registro de abastecimento',
                'verbose_name_plural': 'Registros de abastecimento',
                'ordering': ['-data_abastecimento', '-id'],
            },
        ),
    ]
