# Generated by Django 6.0.4 on 2026-04-23 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0001_initial'),
        ('obras', '0003_aditivocontrato_tipo_alter_obra_status_obra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoLocadoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipamento locado',
                'verbose_name_plural': 'Catalogo de equipamentos locados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LocadoraEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('contato', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Locadora',
                'verbose_name_plural': 'Locadoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LocacaoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_locacao', models.DateField()),
                ('solicitante', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('locado', 'Locado'), ('retirada_solicitada', 'Retirada solicitada'), ('retirado', 'Retirado'), ('cancelado', 'Cancelado')], default='locado', max_length=30)),
                ('data_solicitacao_retirada', models.DateField(blank=True, null=True)),
                ('data_retirada', models.DateField(blank=True, null=True)),
                ('valor_referencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locacoes', to='controles.equipamentolocadocatalogo')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locacoes_equipamentos', to='obras.obra')),
                ('locadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locacoes', to='controles.locadoraequipamento')),
            ],
            options={
                'verbose_name': 'Locacao de equipamento',
                'verbose_name_plural': 'Locacoes de equipamentos',
                'ordering': ['-data_locacao', '-id'],
            },
        ),
    ]
