# Generated by Django 6.0.4 on 2026-04-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0002_equipamentolocadocatalogo_locadoraequipamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoRadarObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('cliente', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('data_orcamento', models.DateField()),
                ('situacao', models.CharField(choices=[('aguardando_resposta', 'Aguardando resposta'), ('em_revisao', 'Em revisao'), ('fechada', 'Fechada'), ('nao_foi_para_frente', 'Nao foi para frente'), ('cancelada', 'Cancelada')], default='aguardando_resposta', max_length=30)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Radar de obra',
                'verbose_name_plural': 'Radar de obras',
                'ordering': ['-data_orcamento', '-id'],
            },
        ),
    ]
