# Generated by Django 6.0.4 on 2026-04-23 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0003_orcamentoradarobra'),
        ('obras', '0003_aditivocontrato_tipo_alter_obra_status_obra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoConcretagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('custo_m3_concreto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('custo_bomba', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adicional_noturno', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adicional_sabado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adicional_m3_faltante', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('volume_minimo_m3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_concretagem', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Contrato de concretagem',
                'verbose_name_plural': 'Contratos de concretagem',
                'ordering': ['-data_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FaturamentoConcretagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_faturamento', models.DateField()),
                ('volume_m3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usou_bomba', models.BooleanField(default=False)),
                ('adicional_noturno_aplicado', models.BooleanField(default=False)),
                ('adicional_sabado_aplicado', models.BooleanField(default=False)),
                ('volume_faltante_m3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('numero_documento', models.CharField(blank=True, max_length=80)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturamentos', to='controles.contratoconcretagem')),
            ],
            options={
                'verbose_name': 'Faturamento de concretagem',
                'verbose_name_plural': 'Faturamentos de concretagem',
                'ordering': ['-data_faturamento', '-id'],
            },
        ),
    ]
