# Generated by Django 6.0.4 on 2026-04-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0004_contratoconcretagem_faturamentoconcretagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoconcretagem',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='faturamentoconcretagem',
            name='data_conferencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faturamentoconcretagem',
            name='fck_traco',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='faturamentoconcretagem',
            name='responsavel_solicitacao',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='faturamentoconcretagem',
            name='status',
            field=models.CharField(choices=[('solicitada', 'Solicitada'), ('executada', 'Executada'), ('conferida', 'Conferida'), ('faturada', 'Faturada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=20),
        ),
        migrations.AddField(
            model_name='faturamentoconcretagem',
            name='tipo_bomba',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='faturamentoconcretagem',
            name='valor_previsto_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='faturamentoconcretagem',
            name='data_faturamento',
            field=models.DateField(verbose_name='Data da concretagem'),
        ),
        migrations.AlterField(
            model_name='faturamentoconcretagem',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nota fiscal'),
        ),
        migrations.AlterField(
            model_name='faturamentoconcretagem',
            name='valor_cobrado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor faturado'),
        ),
    ]
