# Generated by Django 6.0.4 on 2026-04-23 16:17

import django.db.models.deletion
from django.db import migrations, models


def criar_solicitantes_padrao(apps, schema_editor):
    solicitante_model = apps.get_model('controles', 'SolicitanteConcretagem')
    nomes = [
        'Eng. Gession',
        'Eng. Vinicius Melos',
        'Eng. Michael',
        'Eng. Mauricio',
        'Eng. Patrick',
        'Eng. Luiz',
        'Eng Willy',
    ]
    for nome in nomes:
        solicitante_model.objects.get_or_create(nome=nome, defaults={'ativo': True})


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0005_contratoconcretagem_numero_contrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitanteConcretagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitante de concretagem',
                'verbose_name_plural': 'Solicitantes de concretagem',
                'ordering': ['nome'],
            },
        ),
        migrations.RunPython(criar_solicitantes_padrao, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='faturamentoconcretagem',
            name='fck_traco',
            field=models.CharField(blank=True, choices=[('20_mpa', '20 Mpa'), ('25_mpa', '25 Mpa'), ('30_mpa', '30 Mpa'), ('35_mpa', '35 Mpa'), ('acima_35_mpa', 'Acima de 35 Mpa')], max_length=20, verbose_name='FCK/Traco'),
        ),
        migrations.AlterField(
            model_name='faturamentoconcretagem',
            name='tipo_bomba',
            field=models.CharField(blank=True, choices=[('bomba_estacionaria', 'Bomba estacionaria'), ('bomba_lanca', 'Bomba lanca')], max_length=30),
        ),
        migrations.AddField(
            model_name='faturamentoconcretagem',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturamentos', to='controles.solicitanteconcretagem', verbose_name='Responsavel solicitacao'),
        ),
    ]
