# Generated by Django 6.0.4 on 2026-04-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0006_solicitanteconcretagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacaoequipamento',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=150, verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='locacaoequipamento',
            name='prazo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='locacaoequipamento',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Qntd'),
        ),
        migrations.AlterField(
            model_name='locacaoequipamento',
            name='data_locacao',
            field=models.DateField(verbose_name='Data aluguel'),
        ),
        migrations.AlterField(
            model_name='locacaoequipamento',
            name='data_retirada',
            field=models.DateField(blank=True, null=True, verbose_name='Data coleta'),
        ),
        migrations.AlterField(
            model_name='locacaoequipamento',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observacao'),
        ),
        migrations.AlterField(
            model_name='locacaoequipamento',
            name='solicitante',
            field=models.CharField(blank=True, max_length=120, verbose_name='Quem locou'),
        ),
        migrations.AlterField(
            model_name='locacaoequipamento',
            name='status',
            field=models.CharField(choices=[('locado', 'Na obra'), ('retirada_solicitada', 'Ag. coleta'), ('retirado', 'Coletado'), ('cancelado', 'Cancelado')], default='locado', max_length=30),
        ),
        migrations.AlterField(
            model_name='locacaoequipamento',
            name='valor_referencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor'),
        ),
    ]
