# Generated by Django 6.0.4 on 2026-04-29 12:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0007_locacaoequipamento_numero_contrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BombonaCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=80, unique=True)),
                ('capacidade_litros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('localizacao', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('manutencao', 'Manutencao')], default='ativa', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bombona de combustivel',
                'verbose_name_plural': 'Bombonas de combustivel',
                'ordering': ['identificacao'],
            },
        ),
        migrations.AlterField(
            model_name='locacaoequipamento',
            name='status',
            field=models.CharField(choices=[('locado', 'Na obra'), ('aguardando_entrega', 'Ag. entrega'), ('retirada_solicitada', 'Ag. coleta'), ('retirado', 'Coletado'), ('cancelado', 'Cancelado')], default='locado', max_length=30),
        ),
        migrations.CreateModel(
            name='OrdemCompraCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=40, unique=True)),
                ('data_ordem', models.DateField(default=django.utils.timezone.localdate)),
                ('fornecedor', models.CharField(max_length=150)),
                ('solicitante', models.CharField(blank=True, max_length=120)),
                ('tipo_combustivel', models.CharField(choices=[('diesel', 'Diesel'), ('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('arla', 'ARLA'), ('outro', 'Outro')], default='diesel', max_length=20)),
                ('tipo_destino', models.CharField(choices=[('veiculo', 'Veiculo/Maquina'), ('bombona', 'Bombona')], default='veiculo', max_length=20)),
                ('quantidade_litros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_litro_previsto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total_previsto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('solicitada', 'Solicitada'), ('aprovada', 'Aprovada'), ('parcialmente_faturada', 'Parcialmente faturada'), ('faturada', 'Faturada'), ('conferida', 'Conferida'), ('encerrada', 'Encerrada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bombona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_combustivel', to='controles.bombonacombustivel')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_combustivel', to='controles.veiculomaquina')),
            ],
            options={
                'verbose_name': 'Ordem de compra de combustivel',
                'verbose_name_plural': 'Ordens de compra de combustivel',
                'ordering': ['-data_ordem', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoOrdemCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('evento', models.CharField(max_length=80)),
                ('descricao', models.TextField()),
                ('status_anterior', models.CharField(blank=True, max_length=30)),
                ('status_novo', models.CharField(blank=True, max_length=30)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='controles.ordemcompracombustivel')),
            ],
            options={
                'verbose_name': 'Historico da ordem de combustivel',
                'verbose_name_plural': 'Historicos das ordens de combustivel',
                'ordering': ['-data_hora', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('data_emissao', models.DateField()),
                ('litros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_litro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('emitida', 'Emitida'), ('recebida', 'Recebida'), ('conferida', 'Conferida'), ('cancelada', 'Cancelada')], default='emitida', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='controles.ordemcompracombustivel')),
            ],
            options={
                'verbose_name': 'Nota fiscal de combustivel',
                'verbose_name_plural': 'Notas fiscais de combustivel',
                'ordering': ['-data_emissao', '-id'],
                'constraints': [models.UniqueConstraint(fields=('ordem', 'numero'), name='unique_nf_combustivel_por_ordem')],
            },
        ),
    ]
