# Generated by Django 6.0.4 on 2026-04-29 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0008_bombonacombustivel_alter_locacaoequipamento_status_and_more'),
        ('obras', '0003_aditivocontrato_tipo_alter_obra_status_obra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorMaquinaLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('contato', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fornecedor de maquina',
                'verbose_name_plural': 'Fornecedores de maquinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MaquinaLocacaoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='ativa', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Maquina para locacao',
                'verbose_name_plural': 'Catalogo de maquinas para locacao',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoLocacaoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=40, unique=True)),
                ('data_solicitacao', models.DateField(default=django.utils.timezone.localdate)),
                ('solicitante', models.CharField(blank=True, max_length=120)),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('solicitada', 'Solicitada'), ('aprovada', 'Aprovada'), ('aguardando_mobilizacao', 'Aguardando mobilizacao'), ('em_operacao', 'Em operacao'), ('paralisada', 'Paralisada'), ('desmobilizacao_solicitada', 'Desmobilizacao solicitada'), ('desmobilizada', 'Desmobilizada'), ('faturada', 'Faturada'), ('conferida', 'Conferida'), ('encerrada', 'Encerrada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=40)),
                ('tipo_cobranca', models.CharField(choices=[('por_hora', 'Por hora'), ('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('empreitada', 'Empreitada')], default='por_hora', max_length=20)),
                ('data_prevista_inicio', models.DateField(blank=True, null=True)),
                ('data_prevista_fim', models.DateField(blank=True, null=True)),
                ('data_mobilizacao', models.DateField(blank=True, null=True)),
                ('data_inicio_operacao', models.DateField(blank=True, null=True)),
                ('data_solicitacao_desmobilizacao', models.DateField(blank=True, null=True)),
                ('data_desmobilizacao', models.DateField(blank=True, null=True)),
                ('valor_hora', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_diaria', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('franquia_horas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_mobilizacao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_desmobilizacao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_previsto_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('operador_incluso', models.BooleanField(default=False)),
                ('combustivel_incluso', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='controles.fornecedormaquinalocacao')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='controles.maquinalocacaocatalogo')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_locacao_maquinas', to='obras.obra')),
            ],
            options={
                'verbose_name': 'OS de locacao de maquina',
                'verbose_name_plural': 'OS de locacao de maquinas',
                'ordering': ['-data_solicitacao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoLocacaoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('evento', models.CharField(max_length=80)),
                ('descricao', models.TextField()),
                ('status_anterior', models.CharField(blank=True, max_length=40)),
                ('status_novo', models.CharField(blank=True, max_length=40)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='controles.ordemservicolocacaomaquina')),
            ],
            options={
                'verbose_name': 'Historico de locacao de maquina',
                'verbose_name_plural': 'Historicos de locacao de maquinas',
                'ordering': ['-data_hora', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApontamentoMaquinaLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horimetro_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('horimetro_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('horas_paradas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('motivo_parada', models.CharField(blank=True, max_length=255)),
                ('operador', models.CharField(blank=True, max_length=120)),
                ('responsavel_apontamento', models.CharField(blank=True, max_length=120)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='controles.ordemservicolocacaomaquina')),
            ],
            options={
                'verbose_name': 'Apontamento de maquina',
                'verbose_name_plural': 'Apontamentos de maquinas',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalLocacaoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('data_emissao', models.DateField()),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fim', models.DateField(blank=True, null=True)),
                ('horas_faturadas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_maquina', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_mobilizacao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_desmobilizacao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('emitida', 'Emitida'), ('recebida', 'Recebida'), ('conferida', 'Conferida'), ('cancelada', 'Cancelada')], default='emitida', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='controles.ordemservicolocacaomaquina')),
            ],
            options={
                'verbose_name': 'NF de locacao de maquina',
                'verbose_name_plural': 'NFs de locacao de maquinas',
                'ordering': ['-data_emissao', '-id'],
                'constraints': [models.UniqueConstraint(fields=('ordem', 'numero'), name='unique_nf_locacao_maquina_por_ordem')],
            },
        ),
    ]
