# Generated by Django 6.0.4 on 2026-04-30 17:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0009_fornecedormaquinalocacao_maquinalocacaocatalogo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemCompraGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=40, unique=True)),
                ('data_emissao', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('emitida', 'Emitida'), ('aprovada', 'Aprovada'), ('parcialmente_entregue', 'Parcialmente entregue'), ('entregue', 'Entregue'), ('faturada', 'Faturada'), ('encerrada', 'Encerrada'), ('cancelada', 'Cancelada')], default='emitida', max_length=30)),
                ('comprador', models.CharField(blank=True, max_length=120)),
                ('empresa_razao_social', models.CharField(default='AMBAR ENGENHARIA', max_length=180)),
                ('empresa_cnpj', models.CharField(blank=True, max_length=30)),
                ('empresa_endereco', models.CharField(blank=True, max_length=255)),
                ('fornecedor', models.CharField(max_length=180)),
                ('fornecedor_endereco', models.CharField(blank=True, max_length=255)),
                ('fornecedor_bairro', models.CharField(blank=True, max_length=120)),
                ('fornecedor_cidade', models.CharField(blank=True, max_length=120)),
                ('fornecedor_uf', models.CharField(blank=True, max_length=2)),
                ('fornecedor_cpf_cnpj', models.CharField(blank=True, max_length=30)),
                ('fornecedor_cep', models.CharField(blank=True, max_length=20)),
                ('fornecedor_fone', models.CharField(blank=True, max_length=40)),
                ('fornecedor_ie', models.CharField(blank=True, max_length=40)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ordem de compra geral',
                'verbose_name_plural': 'Ordens de compra gerais',
                'ordering': ['-data_emissao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdemCompraGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField(default=1)),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unidade', models.CharField(default='un', max_length=20)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='controles.ordemcomprageral')),
            ],
            options={
                'verbose_name': 'Item da ordem de compra',
                'verbose_name_plural': 'Itens da ordem de compra',
                'ordering': ['item', 'id'],
            },
        ),
    ]
