# Generated by Django 6.0.4 on 2026-05-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0010_ordemcomprageral_itemordemcomprageral'),
        ('financeiro', '0002_fornecedor_contapagar_fornecedor_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoconcretagem',
            name='fornecedor_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_concretagem', to='financeiro.fornecedor'),
        ),
        migrations.AddField(
            model_name='ordemcompracombustivel',
            name='fornecedor_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_combustivel', to='financeiro.fornecedor'),
        ),
        migrations.AddField(
            model_name='ordemcomprageral',
            name='fornecedor_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_compra_gerais', to='financeiro.fornecedor'),
        ),
        migrations.AddField(
            model_name='ordemservicolocacaomaquina',
            name='fornecedor_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_locacao_maquinas', to='financeiro.fornecedor'),
        ),
    ]
