# Generated by Django 6.0.4 on 2026-05-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0012_carrega_radar_obras'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemcomprageral',
            name='condicoes_pagamento',
            field=models.TextField(blank=True),
        ),
    ]
