# Generated by Django 6.0.4 on 2026-05-08 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0013_ordemcomprageral_condicoes_pagamento'),
        ('financeiro', '0002_fornecedor_contapagar_fornecedor_cadastro'),
        ('obras', '0006_carrega_dados_orla_lami'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemcomprageral',
            name='categoria_despesa',
            field=models.CharField(default='material', max_length=30),
        ),
        migrations.AddField(
            model_name='ordemcomprageral',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_compra_gerais', to='financeiro.centrocusto'),
        ),
        migrations.AddField(
            model_name='ordemcomprageral',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_compra_gerais', to='obras.obra'),
        ),
        migrations.CreateModel(
            name='NotaFiscalOrdemCompraGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('recebida', 'Recebida'), ('conferida', 'Conferida'), ('lancada_financeiro', 'Lancada no financeiro'), ('cancelada', 'Cancelada')], default='recebida', max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conta_pagar', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_ordem_compra', to='financeiro.contapagar')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='controles.itemordemcomprageral')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='controles.ordemcomprageral')),
            ],
            options={
                'verbose_name': 'Nota fiscal de ordem de compra',
                'verbose_name_plural': 'Notas fiscais de ordens de compra',
                'ordering': ['-data_emissao', '-id'],
                'constraints': [models.UniqueConstraint(fields=('ordem', 'numero', 'item'), name='unique_nf_oc_geral_por_item')],
            },
        ),
    ]
