# Generated by Django 6.0.4 on 2026-05-08 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0014_ordemcomprageral_categoria_despesa_and_more'),
        ('financeiro', '0004_contapagar_valor_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscalordemcomprageral',
            name='conta_pagar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_ordem_compra', to='financeiro.contapagar'),
        ),
    ]
