# Generated by Django 6.0.4 on 2026-05-25 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0017_faturamentodireto_data_oc_e_dados_park_mall'),
        ('obras', '0006_carrega_dados_orla_lami'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('formato', models.CharField(choices=[('dia', 'Por dia'), ('semana', 'Por semana'), ('mes', 'Por mes')], default='semana', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cronogramas_operacionais', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Cronograma de obra',
                'verbose_name_plural': 'Cronogramas de obras',
                'ordering': ['-data_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LinhaCronogramaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('servico', models.CharField(max_length=255)),
                ('periodos', models.JSONField(blank=True, default=list)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='controles.cronogramaobra')),
            ],
            options={
                'verbose_name': 'Linha do cronograma de obra',
                'verbose_name_plural': 'Linhas dos cronogramas de obras',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
