# Generated by Django 6.0.4 on 2026-05-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0018_cronogramaobra_linhacronogramaobra'),
    ]

    operations = [
        migrations.AddField(
            model_name='linhacronogramaobra',
            name='tipo',
            field=models.CharField(choices=[('servico', 'Servico'), ('geral', 'Item geral')], default='servico', max_length=20),
        ),
    ]
