# Generated by Django 6.0.4 on 2026-06-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0019_linhacronogramaobra_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemcomprageral',
            name='empresa_cnpj',
            field=models.CharField(blank=True, default='35.693.640/0001-09', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordemcomprageral',
            name='empresa_endereco',
            field=models.CharField(blank=True, default='Avenida dos Estados, nº 1205, sala 02, centro - Campo Bom', max_length=255),
        ),
    ]
