# Generated by Django 6.0.4 on 2026-06-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0020_alter_ordemcomprageral_empresa_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemordemcomprageral',
            name='quantidade',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemordemcomprageral',
            name='valor_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='itemordemcomprageral',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='notafiscalordemcomprageral',
            name='quantidade',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='notafiscalordemcomprageral',
            name='valor_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='notafiscalordemcomprageral',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
