# Generated by Django 6.0.4 on 2026-08-16 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0022_orcamentoradarobra_arquivado_temperatura'),
        ('empresas', '0002_cria_empresa_ambar_e_vincula_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronogramaobra',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cronogramas_obras', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='orcamentoradarobra',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_radar', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='ordemcomprageral',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_compra_gerais', to='empresas.empresa'),
        ),
    ]
