# Generated by Django 6.0.4 on 2026-08-16 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0023_cronogramaobra_empresa_orcamentoradarobra_empresa_and_more'),
        ('empresas', '0003_backfill_dados_ambar_fase2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronogramaobra',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cronogramas_obras', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='orcamentoradarobra',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_radar', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='ordemcomprageral',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_compra_gerais', to='empresas.empresa'),
        ),
    ]
