# Generated by Django 6.0.4 on 2026-08-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0027_constraints_empresa_cadastros_operacionais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemcomprageral',
            name='empresa_cnpj',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ordemcomprageral',
            name='empresa_endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ordemcomprageral',
            name='empresa_razao_social',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
