# Generated by Django 6.0.4 on 2026-08-16 01:10

import django.core.validators
import django.db.models.deletion
import empresas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('razao_social', models.CharField(blank=True, max_length=180)),
                ('nome_fantasia', models.CharField(blank=True, max_length=180)),
                ('cnpj', models.CharField(blank=True, max_length=20)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=empresas.models.empresa_logo_upload_to)),
                ('cor_primaria', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Informe uma cor hexadecimal valida, como #1f2937.')])),
                ('cor_secundaria', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Informe uma cor hexadecimal valida, como #e5e7eb.')])),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('administrador_empresa', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_vinculados', to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_vinculadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario da empresa',
                'verbose_name_plural': 'Usuarios das empresas',
                'ordering': ['empresa__nome', 'usuario__username'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'empresa'), name='unique_usuario_empresa')],
            },
        ),
    ]
