# Generated by Django 6.0.4 on 2026-08-16 01:10

from django.conf import settings
from django.db import migrations


def criar_ambar_e_vincular_usuarios(apps, schema_editor):
    Empresa = apps.get_model('empresas', 'Empresa')
    UsuarioEmpresa = apps.get_model('empresas', 'UsuarioEmpresa')
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(user_app_label, user_model_name)

    empresa, _created = Empresa.objects.get_or_create(
        slug='ambar',
        defaults={
            'nome': 'Ambar Engenharia',
            'ativa': True,
        },
    )

    for usuario in User.objects.all():
        UsuarioEmpresa.objects.get_or_create(
            usuario=usuario,
            empresa=empresa,
            defaults={
                'ativo': True,
                'administrador_empresa': usuario.is_superuser,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_ambar_e_vincular_usuarios, migrations.RunPython.noop),
    ]
