# Generated by Django 6.0.4 on 2026-08-16 01:27

from django.db import migrations


def backfill_empresa_ambar(apps, schema_editor):
    Empresa = apps.get_model('empresas', 'Empresa')
    empresa, _created = Empresa.objects.get_or_create(
        slug='ambar',
        defaults={
            'nome': 'Ambar Engenharia',
            'ativa': True,
        },
    )

    Obra = apps.get_model('obras', 'Obra')
    Fornecedor = apps.get_model('financeiro', 'Fornecedor')
    CentroCusto = apps.get_model('financeiro', 'CentroCusto')
    PrevisaoFinanceira = apps.get_model('financeiro', 'PrevisaoFinanceira')
    ContaPagar = apps.get_model('financeiro', 'ContaPagar')
    ContaReceber = apps.get_model('financeiro', 'ContaReceber')
    OrdemCompraGeral = apps.get_model('controles', 'OrdemCompraGeral')
    OrcamentoRadarObra = apps.get_model('controles', 'OrcamentoRadarObra')
    CronogramaObra = apps.get_model('controles', 'CronogramaObra')
    Proposta = apps.get_model('propostas', 'Proposta')
    Empreiteiro = apps.get_model('medicoes', 'Empreiteiro')

    Obra.objects.filter(empresa__isnull=True).update(empresa=empresa)
    Fornecedor.objects.filter(empresa__isnull=True).update(empresa=empresa)
    CentroCusto.objects.filter(empresa__isnull=True).update(empresa=empresa)
    Empreiteiro.objects.filter(empresa__isnull=True).update(empresa=empresa)
    OrcamentoRadarObra.objects.filter(empresa__isnull=True).update(empresa=empresa)
    Proposta.objects.filter(empresa__isnull=True).update(empresa=empresa)

    for model in [PrevisaoFinanceira, ContaPagar, ContaReceber, OrdemCompraGeral, CronogramaObra]:
        for registro in model.objects.filter(empresa__isnull=True).select_related('obra'):
            if getattr(registro, 'obra_id', None):
                empresa_id = registro.obra.empresa_id
            else:
                empresa_id = empresa.id
            model.objects.filter(pk=registro.pk).update(empresa_id=empresa_id)


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_cria_empresa_ambar_e_vincula_usuarios'),
        ('obras', '0007_obra_empresa'),
        ('financeiro', '0015_remove_fornecedor_unique_fornecedor_nome_documento_and_more'),
        ('controles', '0023_cronogramaobra_empresa_orcamentoradarobra_empresa_and_more'),
        ('propostas', '0003_proposta_empresa'),
        ('medicoes', '0010_empreiteiro_empresa_alter_empreiteiro_nome_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_empresa_ambar, migrations.RunPython.noop),
    ]
