# Generated by Django 6.0.4 on 2026-08-16 18:24

import empresas.models
from django.db import migrations, models


def backfill_identidade_ambar(apps, schema_editor):
    Empresa = apps.get_model('empresas', 'Empresa')
    Empresa.objects.filter(slug='ambar').update(
        razao_social='AMBAR ENGENHARIA',
        nome_fantasia='Ambar Engenharia',
        cnpj='35.693.640/0001-09',
        endereco='Avenida dos Estados, nº 1205, sala 02, centro',
        cidade='Campo Bom',
        estado='RS',
        responsavel_tecnico='Eng. Civil Patrick Ruppenthal de Lima',
        crea_responsavel='CREA/RS: 198.404',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_backfill_dados_ambar_fase2'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cabecalho_documentos',
            field=models.ImageField(blank=True, null=True, upload_to=empresas.models.empresa_cabecalho_upload_to),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='empresa',
            name='crea_responsavel',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsavel_tecnico',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rodape_documentos',
            field=models.ImageField(blank=True, null=True, upload_to=empresas.models.empresa_rodape_upload_to),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='empresa',
            name='texto_rodape',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(backfill_identidade_ambar, migrations.RunPython.noop),
    ]
