# Generated by Django 6.0.4 on 2026-08-16 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('empresas', '0004_empresa_cabecalho_documentos_empresa_cep_and_more'),
        ('obras', '0008_alter_obra_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioempresa',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_empresas', to='auth.group'),
        ),
        migrations.AddField(
            model_name='usuarioempresa',
            name='obras_permitidas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_empresas_permitidos', to='obras.obra'),
        ),
    ]
